### ISSUE TITLE
VS Code Dev Container error: Extension can't find Biome if node_moduels isn't in the root of the workspace

### ISSUE THREAD

**Issue by kylerush** [biomejs/biome-vscode#116]
My workspace has a directory structure like this:

```
project/
├── javascript/
│   ├── node_modules/
│   └── package.json
└── python/

```

@biomejs/biome is in the devDependencies in the package.json and it is installed on the file system. i can use the module when running something like `pnpm exec biome format .`. However, when I launch a Visual Studio Code Development Container, I get the following error and auto format on save does not work.

<img width="575" alt="Screenshot 2024-02-02 at 10 01 44 AM" src="https://github.com/biomejs/biome-vscode/assets/150579/7758c5c4-7185-4150-9597-1842842b60f1">

This problem does not happen with other Visual Studio extensions like Prettier and ESLint.

Is there anything I can do on my side or do I need to wait for the improved detection mentioned in #74?

**Comment by kylerush** [comment]
Also want to note that the Biome VS Code extension does get installed and enabled when the container builds and boots up. Here's the devcontainer.json:

```json
{
  "name": "boilerplate",
  "service": "boilerplate",
  "dockerComposeFile": "compose.yml",
  "workspaceFolder": "/workspace",
  "forwardPorts": [5173],
  "postStartCommand": "cd ./javascript && pnpm install",
  "customizations": {
    "vscode": {
      "extensions": [
        "esbenp.prettier-vscode",
        "dbaeumer.vscode-eslint",
        "ms-azuretools.vscode-docker",
        "biomejs.biome"
      ],
      "settings": {
        "terminal.integrated.defaultProfile.linux": "zsh",
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true,
        "[javascript]": {
          "editor.defaultFormatter": "biomejs.biome"
        },
        "[javascriptreact]": {
          "editor.defaultFormatter": "biomejs.biome"
        },
        "[typescript]": {
          "editor.defaultFormatter": "biomejs.biome"
        },
        "[typescriptreact]": {
          "editor.defaultFormatter": "biomejs.biome"
        },
        "[json]": {
          "editor.defaultFormatter": "biomejs.biome"
        },
        "[jsonc]": {
          "editor.defaultFormatter": "biomejs.biome"
        }
      }
    }
  }
}

```

**Comment by nhedger** [comment]
Hey @kylerush,

Thanks for opening this issue.

This is a known limitation.

At present, the extension only looks for Biome in the `node_modules` folder at the root of your workspace. We might do something about it in the future, but it's going to require some more thinking.

Unfortunately, the improved detection discussed in #74 does not include a fix for this.

**Comment by aquirdTurtle** [comment]
I have the same problem as the OP and it makes it rather difficult to configure biome for my projects. I think for other extensions I've seen a setting to just specify the workspace directory for the linter to use, to look for node_modules and config files like biome.json.

**Comment by dmg-egg** [comment]
Yeah, this is a painful problem for us. One of the bigger goals of Biome is to standardize code across the team. That's one of the bigger goals for Dev Containers, as well. But currently, they don't play well together.

**Comment by epicwhale** [comment]
+1 facing the same issue where I have a backend and frontend directory in the root folder and biome is only inside frontend/node_modules 

I am trying to migrate from prettier/eslint over to biome but I'm not able to figure out what the like for like setup for it is supposed to be in this instance
