### ISSUE TITLE
🐛 VS Code Format on Save Ignores Biome.json Directives

### ISSUE THREAD

**Issue by sohibegit** [biomejs/biome-vscode#124]
### Extension version

2.1.2

### Biome version

1.5.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

The formatOnSave functionality within Visual Studio Code should adhere to the include and ignore directives as defined in the biome.json configuration file. For instance, consider the following configuration settings:

```json
{
  "files": {
    "include": ["functions/*.js", "types.ts"],
    "ignore": ["schemas/*.json"]
  }
}

```
This configuration specifies that formatOnSave should only apply to JavaScript files in the functions directory and the TypeScript file types.ts, while explicitly excluding JSON files in the schemas directory.

### Steps to reproduce

Navigate to any file that should be ignored, make a change to it, and then save the file. You'll notice that it gets formatted despite being listed as ignored.

### Expected behavior

Upon saving, files specified under the ignore directive in biome.json are expected to remain unaltered by the formatOnSave feature, preserving their original formatting without applying any auto-formatting rules.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by nhedger** [comment]
Hey,

Thanks for opening this issue.

I was able to reproduce it with the latest stable version (1.5.3), but this is [a known issue that has already been fixed](https://github.com/biomejs/biome/pull/1680), and a fix will be released with the next version.

Could you try the latest nightly (`1.5.3-nightly.6cbf1c7`) and tell me if you can still reproduce this behavior? 

It also is worth noting that if you have configured a different default formatter for `.json` files, they might get formatted, just not by Biome, so keep an eye out for that. When in doubt, you can always open the Biome trace output to see if the LSP in formatting documents or not.

**Comment by sohibegit** [comment]
> Hey,
> 
> Thanks for opening this issue.
> 
> I was able to reproduce it with the latest stable version (1.5.3), but this is [a known issue that has already been fixed](https://github.com/biomejs/biome/pull/1680), and a fix will be released with the next version.
> 
> Could you try the latest nightly (`1.5.3-nightly.6cbf1c7`) and tell me if you can still reproduce this behavior?
> 
> It also is worth noting that if you have configured a different default formatter for `.json` files, they might get formatted, just not by Biome, so keep an eye out for that. When in doubt, you can always open the Biome trace output to see if the LSP in formatting documents or not.

Hey,

Thanks for the quick help! I tested with the latest nightly (1.5.3-nightly.6cbf1c7) and the issue is fixed. Appreciate the heads-up about the .json formatter and Biome trace output as well.

Looking forward to the fix in the next release!

**Comment by nhedger** [comment]
Thank you for confirming!
