### ISSUE TITLE
📎 Yarn PnP support

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome-vscode#126]
### Summary

This task tracks the implementation of [Yarn PnP](https://yarnpkg.com/features/pnp) support for resolving the `biome` binary from a project's dependencies. 

Yarn PnP uses a different strategy for installing dependencies that does not involve a `node_modules` folder, which is what we've been relying on with other package managers.

Ideally, we shouldn't have to rely on executing an external command to find the path to the binary, but it is unclear if that's even possible.

### Reference

- https://yarnpkg.com/features/pnp

### Contributing

If you'd like to contribute and implement this, please make it known in the comments so we can assign you to the task.

**Comment by roblillack** [comment]
Added a pull request for this: https://github.com/biomejs/biome-vscode/pull/134
