### ISSUE TITLE
📎 NixOS support

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome-vscode#127]
### Summary

This task tracks the implementation of [NixOS](https://nixos.org/) support for resolving the `biome` binary from a project's dependencies. 

### Reference

- https://nixos.org/
- https://nixos.org/guides/how-nix-works#nixos

### Contributing

If you'd like to contribute and implement this, please make it known in the comments so we can assign you to the task.

**Comment by nhedger** [comment]
> When considering the bundled biome-lsp binary, it may be a better choice to switch to the -musl build, which appears to work out of the box on NixOS:
> 
> ![image](https://private-user-images.githubusercontent.com/10835147/303940891-b89fd17f-8f5e-481d-adb1-f98f46f7f11f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODE4NzQsIm5iZiI6MTcwNzY4MTU3NCwicGF0aCI6Ii8xMDgzNTE0Ny8zMDM5NDA4OTEtYjg5ZmQxN2YtOGY1ZS00ODFkLWFkYjEtZjk4ZjQ2ZjdmMTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE5NTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjA0MjAzY2U5ZDNjNWRlYjQxYTJmOGMwZTExMmZiYzk4YjJlY2Q0NjNlZWZlMDdlNTlkYjFjNDFhMjcwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4DWXzUdryBSF2BXfK3Clq4POZbEED9RLu5BisvGToA)
> 
> ![image](https://private-user-images.githubusercontent.com/10835147/303940942-3f55ae59-ea3f-4851-964f-29dfa48d474c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODE4NzQsIm5iZiI6MTcwNzY4MTU3NCwicGF0aCI6Ii8xMDgzNTE0Ny8zMDM5NDA5NDItM2Y1NWFlNTktZWEzZi00ODUxLTk2NGYtMjlkZmE0OGQ0NzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE5NTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOGVhZWZkNDI0YzM4Mjc5ODlhNDhlNDQzMGQ0Y2RhNzU0NWY0MDJhYzRlNzdlNGVjNWY2ZTY0ZTJlZjRiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ybmFp7Vko19ZhjW8HimVbKOhReSPQ4rowPo5shnW04Y)
> 
> PS. _"no such file (...)"_ is a typical error message for broken binaries

Not sure how it relates to this issue?

**Comment by Zaczero** [comment]
Sorry for the missing explanation. This is an issue related to the NixOS support, that the bundled LSP binary does not work, which I forgot to mention.

![image](https://github.com/biomejs/biome-vscode/assets/10835147/879fea41-9c4f-4298-ac9e-8d5052a99bd6)

```log
Extension bundle does not include the prebuilt binary
Biome binary found at /home/user/.config/Code/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/user/.config/Code/User/globalStorage/biomejs.biome/server/biome
[Error - 8:41:13 PM] Biome client: couldn't create connection to server.
Error: spawn /home/user/.config/Code/User/globalStorage/biomejs.biome/server/biome ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[cli-stdout] end
[cli-stdout] finish
[cli-stderr] end
[cli-stderr] finish
[cli-stderr] close
[cli] close -2
[cli-stdout] close
```

**Comment by kkimdev** [comment]
Hi, is this truly fixed?  I tried to run biome nightly on NixOS(on CI) and getting this error.

```
# Version: 1.8.4-nightly.a579bf7
/drone/src/node_modules/.pnpm/@biomejs+biome@1.8.4-nightly.a579bf7/node_modules/@biomejs/biome/bin/biome:68
		throw result.error;
		^

Error: spawnSync /drone/src/node_modules/.pnpm/@biomejs+cli-linux-x64@1.8.4-nightly.a579bf7/node_modules/@biomejs/cli-linux-x64/biome ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at Object.spawnSync (node:child_process:875:24)
    at Object.<anonymous> (/drone/src/node_modules/.pnpm/@biomejs+biome@1.8.4-nightly.a579bf7/node_modules/@biomejs/biome/bin/biome:50:42)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /drone/src/node_modules/.pnpm/@biomejs+cli-linux-x64@1.8.4-nightly.a579bf7/node_modules/@biomejs/cli-linux-x64/biome',
  path: '/drone/src/node_modules/.pnpm/@biomejs+cli-linux-x64@1.8.4-nightly.a579bf7/node_modules/@biomejs/cli-linux-x64/biome',
  spawnargs: [
    'lint',
    '--error-on-warnings',
    '--max-diagnostics=10000',
    '--changed',
    '--no-errors-on-unmatched'
  ]
}

```

**Comment by kkimdev** [comment]
Oh sorry, NVM, I thought this was https://github.com/biomejs/biome/issues .
