### ISSUE TITLE
Enable VSCode for `vue`, `svelte` and `astro` files

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome-vscode#140]
## Descriptions

This issue has more background: https://github.com/biomejs/biome/issues/1719

## Technical changes

From Discord

> For the upcoming partial support of vue, svelte and astro we have to change the VSCode extension. At the moment the extension activates when specific file langauges are opened, but that won't work for astro files
This means that we have to trigger extension in a more generic way, and "disable" it dynamically by checking the extension file that is currently about to open

**Comment by nhedger** [comment]
Why wouldn't that work ? Couldn't we just target the `astro` and `vue` languages ?

<img width="1016" alt="Screenshot 2024-02-15 at 14 15 41" src="https://github.com/biomejs/biome-vscode/assets/649677/5d8e6800-70b6-41a6-9477-4088c16afd09">

**Comment by ematipico** [comment]
Unless the documentation is outdated, Astro isn't part of this list: https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers

**Comment by nhedger** [comment]
Oh right it is provided by the Astro extension.

**Comment by nhedger** [comment]
That being said, maybe we can use a pattern instead of a language. I'd have to test.

```ts
const documentSelector: DocumentFilter[] = [
	// ...
    { pattern: "**/*.astro", scheme: "file"}
];
```

**Comment by nhedger** [comment]
Unfortunately, I can't get the document filter to match the files without specifying the `language`.

Honestly, i don't think it would be too far fetched to ask the users to have the Astro, or Vue extensions installed in their editor.

**Comment by ematipico** [comment]
I opened an issue here https://github.com/microsoft/vscode/issues/205296

Let's hope for the best!

**Comment by nhedger** [comment]
Vue is on the list of known files, but the language filter does not work if the vue extension is not installed, so my guess this only serves to recommend installing the corresponding extension.
