### ISSUE TITLE
🐛 Missing information in the contributing section

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome-vscode#147]
### Extension version

main

### Biome version

main

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Description

The current `CONTRIBUTING.md` document doesn't explain how a contributor can bundle the VSCode extension, and it doesn't explain how to launch VSCode with the bundled extension. 

### Steps to reproduce

1. Open the document `CONTRIBUTING.md`
2. Check the `Development` header
3. It mentions a watch mode for debugging, but it's unclear how it works. I pressed in `F5`, but it didn't do anything

### Expected behavior

I would expect more information for people who aren't accustomed to the developments of the project

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by nhedger** [comment]
AFAIK, the <kbd>F5</kbd> shortcut is VS Code's default to start the debugger, so it should work out of the box. Could you try running the `Debug: Start Debugging` command from the command palette and see if this works?

**Comment by ematipico** [comment]
I pressed F5 when I opened VSCode, and it didn't do anything. I opened a project and went to the plugin page, and it worked.

Does F5 work when a project is open?

**Comment by nhedger** [comment]
Should work within the extension's project.


https://github.com/biomejs/biome-vscode/assets/649677/178e23c2-c387-457c-a998-4539551fe842

**Comment by ematipico** [comment]
Oh, then I didn't understand how it works 😅

Sorry, looking at this flow for the first time and I'm having a hard time

**Comment by nhedger** [comment]
Addressed in https://github.com/biomejs/biome-vscode/pull/321
