### ISSUE TITLE
🐛 Possibility to use different Biome configurations in VSCode?

### ISSUE THREAD

**Issue by mcfdez** [biomejs/biome-vscode#174]
### VS Code version

1.87.2

### Extension version

2.2.2

### Biome version

1.6.1

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

Hello friends. I am testing Biome in a monorepo project in Typescript and running Biome through the CLI works correctly, as I can pass the "--config-path" parameter to point out which config file I want to use.

However, the VSCode extension explains that it looks for biome.js in the root of the project. Is it possible to show Lint errors or format the code using a custom config path?

### Steps to reproduce

1. Create a new project with multiple applications. 
2. Add a Biome configuration for one of these projects.
3. Open a file of one project (where we added the Biome config).

### Expected behavior

Should show Lint errors associated with the Biome configuration for an especific project.

### Does this issue occur when using the CLI directly?

No

**Comment by arendjr** [comment]
Unfortunately not, sorry. We have an open issue for this: https://github.com/biomejs/biome/issues/1630
