### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by hornta** [biomejs/biome-vscode#182]
### VS Code version

1.87.2

### Extension version

2.2.2

### Biome version

1.6.3

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

vscode is not reporting all biome errors at once. It feels like Biome isn't running in the background, but when I first open a file with errors in it, then vscode knows about the "error".

![image](https://github.com/biomejs/biome-vscode/assets/4553604/c59f6ced-0666-4ecf-ab87-ff08f214ee84)
Here it says 7, but in reality when I run biome in CLI I have around 100. I've waited a very long time in case biome is still figuring out all errors.

### Steps to reproduce

N/A

### Expected behavior

I expect to see all errors in the tab "Errors".

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by ematipico** [comment]
Not a bug. Feel free to open a discussion and propose this feature
