### ISSUE TITLE
🐛 Outdated documentation 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome-vscode#188]
### VS Code version

latest 

### Extension version

latest 

### Biome version

latest 

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Description

The readme documentation is outdated. At the very bottom, the options are old and the new ones aren't listed.

### Steps to reproduce

Just the readme

### Expected behavior

It should list all the new added options 

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by nhedger** [comment]
I'm wondering whether the README should instead include a link to the documentation page on the website. This would make it easier to maintain it in a single place.

**Comment by ematipico** [comment]
Having it in the readme allows people to read the documentation straight from VSCode, which would work offline, too. But it's nice to have. 

I don't mind linking the website. However, we should always remember to update the documentation.

**Comment by nhedger** [comment]
Closing in favor of https://github.com/biomejs/website/pull/974.
