### ISSUE TITLE
🐛 Biome plugin giving me a wrong error

### ISSUE THREAD

**Issue by vbasky** [biomejs/biome-vscode#194]
### VS Code version

1.88.1

### Extension version

2.2.2

### Biome version

1.6.4

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

Actual Behaviour - Without Biome Plugin turned on

<img width="624" alt="Screenshot 2024-04-12 at 3 13 48 PM" src="https://github.com/biomejs/biome-vscode/assets/287302/07f1747a-28e0-43da-bc3b-2f7451b9a505">

With it turned on

<img width="786" alt="Screenshot 2024-04-12 at 3 17 07 PM" src="https://github.com/biomejs/biome-vscode/assets/287302/27702bce-6d8d-408b-a2c3-7bb7557c3c7f">

And when I save because I have format on save option turned on, the import gets modified to import type

<img width="694" alt="image" src="https://github.com/biomejs/biome-vscode/assets/287302/150921d4-0762-42a2-b56f-69b8c6624882">

### Steps to reproduce

Open any NestJs project that has an additional service added as a module

Biome interprets the service file differently as a type

### Expected behavior

Biome to not offer to mark a service file in NestJs as a type

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by Sec-ant** [comment]
See: https://github.com/biomejs/biome/issues/2003, https://github.com/biomejs/biome/issues/2038 and https://github.com/biomejs/biome/issues/2309
