### ISSUE TITLE
🐛 Minor annoyance: Choosing nightly build shouldn't display "update available"

### ISSUE THREAD

**Issue by Xerios** [biomejs/biome-vscode#195]
### VS Code version

1.88.1

### Extension version

2.2.2

### Biome version

1.6.4-nightly

### Operating system

- [X] Windows
- [X] macOS
- [X] Linux

### Description

It is a bit distracting having a big yellow bar showing update is available while using a nightly build when it's not really the case.
Then again, perhaps this is due to the nightly version mistakenly having the same version (and not one version above) as the one that was already released.

### Steps to reproduce

Select a nightly build from the version list on the status bottom bar of vscode, which then misleadingly shows that there's a new update.

### Expected behavior

I would expect while having `1.6.4-nightlyXXXX` build selected that when it notifies that there's a new version that it would an upgrade to `1.6.5` and not a downgrade to `1.6.4`

### Does this issue occur when using the CLI directly?

No

**Comment by ematipico** [comment]
> due to the nightly version mistakenly having the same version (and not one version above) as the one that was already released.

I thought we fixed it, but it seems we didn't :(

**Comment by nhedger** [comment]
No longer an issue in the upcoming v3.
