### ISSUE TITLE
Setup Renovate

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome-vscode#197]
We've started using Renovate in the other repositories, let's replace dependabot with Renovate here too.

**Comment by AshutoshNanaware** [comment]
Hi @nhedger , I am working on this. My approach would be to delete Dependabot and add a new configuration with Renovate. Also, I think once this is done, we need to disable Dependabot alerts and security updates from the repo. Could you please assign this to me to avoid any conflicts?

**Comment by nhedger** [comment]
Sounds good! Appreciate the help!

**Comment by AshutoshNanaware** [comment]
@nhedger I have added renovate from other repos, so if you need any modifications to current configurations please let me know. Also we will need to enable renovate for this repo.

**Comment by nhedger** [comment]
Thanks, I'll have a look in a bit!
