### ISSUE TITLE
🐛 error access vscode extensions

### ISSUE THREAD

**Issue by wcastand** [biomejs/biome-vscode#20]
### Environment information

biome rage return :

```block
Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.1.2
```

yarn v3 on a monorepo.

### What happened?

update vscode extension got an error:

```
Biome client: couldn't create connection to server.

/node_modules/.bin/biome: Permission denied
```

Discord asked me to run this command and it fixed the issue:

```chmod +x ./node_modules/.bin/biome```

been asked to reference this issue: https://github.com/rome/tools/pull/3800

### Expected result

update the vscode extension and it works

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
It's been 2 months since the last message, I assume the bug is fixed.

If anybody happens to arrive here, **please open a new issue**.
