### ISSUE TITLE
🐛 FormattingExtension 'Biome' is configured as formatter but it cannot format 'TypeScript JSX'-files

### ISSUE THREAD

**Issue by Cygnusfear** [biomejs/biome-vscode#206]
### VS Code version

1.88.1 (Universal)

### Extension version

2.2.2

### Biome version

1.7.1

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

VS gives a warning that `FormattingExtension 'Biome' is configured as formatter but it cannot format 'TypeScript JSX'-files` on a regular TSX file

### Steps to reproduce

.

### Expected behavior

Should work as usual

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by Cygnusfear** [comment]
This also seems to happen on regular TS files: `FormattingExtension 'Biome' is configured as formatter but it cannot format 'TypeScript'-files`

**Comment by nhedger** [comment]
This could indicate that the extension wasn't able to start an LSP session.

If you go to the output panel, could you see if there's an output for Biome, and if so paste the contents here.

**Comment by Cygnusfear** [comment]
I don't get any output in the panel. It puts the biome plugin on slash-eye
icon and says 'The current file is not supported or ignored by Biome' in
the tooltip

**Comment by nhedger** [comment]
Would you mind sharing a screen capture (video)? This would help with troubleshooting.

**Comment by Cygnusfear** [comment]
Of course, let me know if there's anything else that could help.
![Screen 2024-05-11 at 07 15 17](https://github.com/biomejs/biome-vscode/assets/2925132/8799ab6c-f69f-440c-9aa7-0202303fb4a8)
<img width="540" alt="Screenshot 2024-05-11 at 07 16 48" src="https://github.com/biomejs/biome-vscode/assets/2925132/abc44d0f-5268-4ba9-bc57-0f614bcf5730">
<img width="547" alt="Screenshot 2024-05-11 at 07 16 53" src="https://github.com/biomejs/biome-vscode/assets/2925132/51ccfa3b-d00d-42f6-853b-43ab066a7fb7">

**Comment by Sec-ant** [comment]
Can you check if there're any issues in your biome configuration (`biome.json` or `biome.jsonc`)? Failing to parse the configuration files can also lead to this kind of errors.

**Comment by Cygnusfear** [comment]
Yes, that was it. A leftover comma. 👍

Probably be helpful to have some better error feedback around that.

**Comment by ematipico** [comment]
> Yes, that was it. A leftover comma. 👍
> 
> Probably be helpful to have some better error feedback around that.
> 
> Awesome, thank you all for your help 🙏♥️

I believe there's an error printed in the output tab of the extension.
