### ISSUE TITLE
🐛 : Decorators are not valid here. biome(parse)

### ISSUE THREAD

**Issue by MagnusHJensen** [biomejs/biome-vscode#231]
### VS Code version

1.89.1

### Extension version

2.2.3

### Biome version

1.7.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

When using NestJs and using parameter decorators, biome complains about it not being valid.
![image](https://github.com/biomejs/biome-vscode/assets/32039051/4e37394c-e8d9-4bb4-ac83-c7f6efea6743)

If disabling it in the `biome.json` file with the following code:
```json
"javascript": {
		"parser": {
			"unsafeParameterDecoratorsEnabled": true
		}
	},
```

The cli tool, can run fine, however the VScode extension still reports it as a problem.

### Steps to reproduce

Decorate a parameter, and allow for unsafeParameterDecorators, and see vscode extension still failing.

### Expected behavior

For the VSCode extension to report the same issues as the cli tool does.

### Does this issue occur when using the CLI directly?

No

**Comment by ematipico** [comment]
VSCode isn't able to load your configuration file. Where is it placed? What do you see in the output/logs? Did you read the troubleshooting section?

**Comment by MagnusHJensen** [comment]
It's a monorepo setup, and it goes like this:

app/
- package.json (with biome/biomejs installed as devDep)
- biome.json
- packages/backend/
- - package.json (with biome/biomeJs installed as devDep)
- - biome.json (this one extends the root biome.json)

Here is the gist for the four files.
https://gist.github.com/MagnusHJensen/a5d4de47b1581436794149b3374fb466

**Comment by MagnusHJensen** [comment]
Update: Just using the root configuration file and no other configuration files inside the packages in a monorepo, seems to work.

**Comment by ematipico** [comment]
I was about to say that. Nested config files aren't supported
