### ISSUE TITLE
🐛 "useNodejsImportProtocol": "off"  Didn't work

### ISSUE THREAD

**Issue by wuchuguang** [biomejs/biome-vscode#235]
### VS Code version

1.89.1

### Extension version

v2024.5.251958 

### Biome version

1.8.0

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

my beiome.js code
``` json
{
	"$schema": "https://biomejs.dev/schemas/1.8.0/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"linter": {
		"ignore": [
			"**/node_modules/**",
			"**/dist/**",
			"**/build/**",
			"**/run/**",
			"**/test/**"
		],
		"enabled": true,
		"rules": {
			"recommended": true,
			"style": {
				"useNodejsImportProtocol": "off"
			}
		}
	}
}

```

![image](https://github.com/biomejs/biome-vscode/assets/1677247/7d50bc9e-954e-479c-b936-ca3a790237bd)

"useNodejsImportProtocol": "off"  Didn't work

### Steps to reproduce

1、I configured setting.json as provided by the plugin
2、biome init  biome.js config
3、change biome.js like up 

### Expected behavior

4、Now in my code, I can't use require('path').
5、 npx biome lint   is ok.

### Does this issue occur when using the CLI directly?

No

### Logs

```plain text
that is all
```

**Comment by wuchuguang** [comment]
The biome.js configuration doesn't seem to be working, is vscode-plugin.biome not using biome.js?

**Comment by wuchuguang** [comment]
![image](https://github.com/biomejs/biome-vscode/assets/1677247/ac835191-15da-4e96-87a0-ad0c42128725)
![image](https://github.com/biomejs/biome-vscode/assets/1677247/6821214c-d83d-42eb-b457-d41bd22c88d3)

**Comment by wuchuguang** [comment]
![image](https://github.com/biomejs/biome-vscode/assets/1677247/d0f7f4e2-1e95-425e-831f-855452b87854)

**Comment by Sec-ant** [comment]
The configuration file is `biome.json` not `biome.js`.

And where do you put the configuration file?

**Comment by wuchuguang** [comment]
> The configuration file is `biome.json` not `biome.js`.
> 
> And where do you put the configuration file?

yes, my is biome.json

**Comment by wuchuguang** [comment]
![image](https://github.com/biomejs/biome-vscode/assets/1677247/c763b5bb-0617-4ea7-bce6-dfb8d4a2007c)

**Comment by ematipico** [comment]
Is your configuration at the root of your project?

**Comment by wuchuguang** [comment]
> Is your configuration at the root of your project? From the look of it, it isn't, that's why it doesn't work.

biome.json in my project.

I have multiple projects in my workspace

**Comment by wuchuguang** [comment]
![image](https://github.com/biomejs/biome-vscode/assets/1677247/c27a6150-a2e2-4c9a-8451-3f6bffb960f8)

**Comment by Sec-ant** [comment]
We have limitations in multi-root workspace support, please check the doc: https://biomejs.dev/reference/vscode/#my-biomejson-file-is-ignored-in-a-multi-root-workspace

**Comment by ematipico** [comment]
Since v1.8 we support LSP workspaces. @wuchuguang can you create a reproduction?

**Comment by Sec-ant** [comment]
Sorry

**Comment by wuchuguang** [comment]
s 

> Since v1.8 we support LSP workspaces. Docs are outdated. @wuchuguang can you create a reproduction?

I'll try using the local LSP

**Comment by wuchuguang** [comment]
1、my workspace only one project, 
2、project/biome.json
3、test.js
     const path = require('path') // show biome error
4、test/biome.json
5、 test/test.js
     const path = require('path') // show biome error
![image](https://github.com/biomejs/biome-vscode/assets/1677247/c3dd8c56-7c96-4632-ac7c-6bf2809527cd)

biome.json
``` json
{
    "$schema": "https://biomejs.dev/schemas/1.8.0/schema.json",
    "organizeImports": {
        "enabled": true
    },
    "linter": {
        "enabled": true,
        "rules": {
            "recommended": true,
            "style": {
                "useNodejsImportProtocol": "off"
            }
        }
    }
}
```

**Comment by ematipico** [comment]
I believe the issue comes from the extension itself that can't correctly resolve the Biome binary from a workspace project.
