### ISSUE TITLE
🐛 Biome doesn't format on save

### ISSUE THREAD

**Issue by rikusen0335** [biomejs/biome-vscode#238]
### VS Code version

1.90.0

### Extension version

2.3.0

### Biome version

1.8.0

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

As title says, biome won't format codes in vscode when Ctrl + S.
`Ctrl + Shift + P` > `Format Document...` will correctly format.

### Steps to reproduce

1. Just Ctrl + S

### Expected behavior

Biome will format codes when Ctrl + S

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs
outputs from VS Code Biome

```plain text
Biome binary found at s:\workspace\konomi-hp\node_modules\.pnpm\@biomejs+cli-win32-x64@1.8.0\node_modules\@biomejs\cli-win32-x64\biome.exe
Copying binary to temporary folder: file:///c%3A/Users/rikusen/AppData/Roaming/Code/User/workspaceStorage/a651e6ef88d0cffc954257946c90e77a/biomejs.biome/biome.exe
Executing Biome from: c:\Users\rikusen\AppData\Roaming\Code\User\workspaceStorage\a651e6ef88d0cffc954257946c90e77a\biomejs.biome\biome.exe
[cli-stdout] data 29
[cli] exit 0
Connecting to "\\.\pipe\biome-service-1.8.0" ...
[Info  - 21:10:29] Server initialized with PID: 35248
```

**Comment by heliocj** [comment]
Same here. But mine doesn't work even with "Format Document...". I have to run CLI (npx @biomejs/biome format --write <files>) to format the files correctly. And my Settings at VsCode are configured.

"editor.formatOnSave": true,
"editor.defaultFormatter": "biomejs.biome",

**Comment by Sec-ant** [comment]
Can anyone encounter this issue share a repo for reproduction / a screen record of the full editor window that shows the problem, and share the [daemon logs](https://biomejs.dev/guides/integrate-in-editor/#daemon-logs) when this issue happens? (You can run `biome clean` to clear the existing logs before starting logging)

Otherwise it's difficult to debug.

**Comment by heliocj** [comment]
Woot! After some hours trying everything around, in my case, I just found some options that after deactivated them, my Biome just back to work like a charm. 

I'll let this information here if someone having the same issue at windows.

I just migrated those eslint+prettier configurations to Biome json file and deactivated these two options in my VsCode settings (those both were activated for some reason): 
![configs](https://github.com/biomejs/biome-vscode/assets/69656528/be48e5c0-c990-4ca7-be56-ff68a3f96666)

**Comment by rikusen0335** [comment]
I dont have reproducible playground due to I don't know what is causing this, but well, here's daemon logs: https://hastebin.skyra.pw/eloyaxulaj.yaml

Tried @heliocj 's workaround but they didn't work. One thing different is that I can format them correctly with biome cli

**Comment by ematipico** [comment]
> I dont have reproducible playground due to I don't know what is causing this, but well, here's daemon logs: [hastebin.skyra.pw/eloyaxulaj.yaml](https://hastebin.skyra.pw/eloyaxulaj.yaml)
> 
> Tried @heliocj 's workaround but they didn't work. One thing different is that I can format them correctly with biome cli

The logs don't show any formatting request, which means it's possible you have some client setting which prevents from using Biome as default formatter.

**Comment by rikusen0335** [comment]
@ematipico I guess I set VSCode completely :(
Here is the config:
```json
{
  "editor.defaultFormatter": "biomejs.biome",
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit"
  },
}
```

**Comment by ematipico** [comment]
Really weird. Can you share with us the repository, or a minimal reproduction?

**Comment by rikusen0335** [comment]
Yeah of course, I will make a minimal reproduction tomorrow

**Comment by rikusen0335** [comment]
@ematipico https://github.com/rikusen0335/biome-minimal-reproduction
Now TOMORROW, here's minimal repro. 
Just kidding sorry for late :(

**Comment by rikusen0335** [comment]
@nhedger Okay, will try confirm my settings again and try that project specific settings.

**Comment by rikusen0335** [comment]
@heliocj Btw could you tell me what is that in your pics shown the bar contains "dip_historicos.notes" and how do you set the activity bar on right bottom??

**Comment by nhedger** [comment]
> @heliocj Btw could you tell me what is that in your pics shown the bar contains "dip_historicos.notes" and how do you set the activity bar on right bottom??

Not my screenshot, I'm afraid :)

**Comment by rikusen0335** [comment]
> Not my screenshot, I'm afraid :)

Yeah it's @heliocj 's. I'm sorry it is not related to issue but I just wanna know

**Comment by heliocj** [comment]
> @heliocj Btw could you tell me what is that in your pics shown the bar contains "dip_historicos.notes" and how do you set the activity bar on right bottom??

Sorry for that off-topic guys XD

Yeah, I'm using the plugin: Apc Customize UI++, to change my UI on VSCode. 

That "dip_historicos.notes", is just a file that I use to write my notes about the project that I'm still in change. I`m using the plugin: Notes. This plugin use format of preview the MD styles with commands that help me to style the notations.

**Comment by rikusen0335** [comment]
@heliocj Oh, thank you so much!
After much time of googling, I could find they are able to do with:
```json
{
  "workbench.editor.pinnedTabsOnSeparateRow": true,
  "workbench.activityBar.location": "bottom",
}
```
But probably extension is better.

Tho sorry for offtopic ;)
I just wanna spread knowledge if random person see this

**Comment by rikusen0335** [comment]
Now tried this:
> You can try overriding this by creating a .vscode/settings.json file with the following contents:

But unfortunately it doesn't worked :(

**Comment by Loscho19** [comment]
i have the same issue
  
```
"editor.defaultFormatter": "esbenp.prettier-vscode",
"prettier.prettierPath": "/Users/fabian/.config/yarn/global/node_modules/prettier/index.cjs",
//"biome.lspBin": "/Users/fabian/.config/yarn/global/node_modules/@biomejs/biome/bin/biome",
"editor.formatOnType": false,
"editor.formatOnPaste": false,
"editor.formatOnSave": true,
"[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
```

**Comment by Loscho19** [comment]
formatOnSave dont work for me if i use biomejs.biome

**Comment by nhedger** [comment]
You may want to provide a minimal reproduction repo. It's hard to tell without context.

**Comment by rikusen0335** [comment]
@Loscho19 In case lazy to create minimal reproduction: https://github.com/rikusen0335/biome-minimal-reproduction

**Comment by rikusen0335** [comment]
@nhedger So uh, can I get stcktraces for biome like when I press `Ctrl + S`?

**Comment by setchy** [comment]
I have been having issues on two separate macs with biome format on save actions for the past 1-2 months.  Before this, it was working a treat.

Removing the files within `/Users/<UserName>/Library/Caches/dev.biomejs.biome` as mentioned on https://biomejs.dev/guides/integrate-in-editor/#daemon-logs resolved my issue.  

The files removed were
```
biome-logs
biome-socket-1.6.4
biome-socket-1.7.0
biome-socket-1.7.1
biome-socket-1.7.2
biome-socket-1.7.3
biome-socket-1.8.0
biome-socket-1.8.1
biome-socket-1.8.2
biome-socket-1.8.3
```

**Comment by rikusen0335** [comment]
Here, daemon log:
```
└─┐biome_lsp::handlers::analysis::code_actions{uri=file:///w%3A/[project-name]/components/pages/home/HomePage.tsx, range=Range { start: Position { line: 27, character: 19 }, end: Position { line: 27, character: 19 } }, only=None, diagnostics=[]}
  ├─  0ms DEBUG biome_service::workspace::server File capabilities: Js(JsFileSource { language: TypeScript { definition_file: false }, variant: Jsx, module_kind: Module, version: ES2022, embedding_kind: None }) BiomePath { path: "w:\\[project-name]\\components\\pages\\home\\HomePage.tsx" }
  ├─  0ms DEBUG biome_service::workspace The file has the following feature sets: 
  │ {OrganizeImports: Supported, Search: FileNotSupported, Format: Supported, Lint: Supported}
  ├─  0ms DEBUG biome_lsp::handlers::analysis Cursor range 1030..1030
  ├─  0ms DEBUG biome_service::workspace::server File capabilities: Js(JsFileSource { language: TypeScript { definition_file: false }, variant: Jsx, module_kind: Module, version: ES2022, embedding_kind: None }) BiomePath { path: "w:\\[project-name]\\components\\pages\\home\\HomePage.tsx" }
  └─┐biome_service::file_handlers::javascript::code_actions{}
    └─┐biome_service::file_handlers::javascript::Code actions JavaScript{range=1030..1030, path=BiomePath { path: "w:\\[project-name]\\components\\pages\\home\\HomePage.tsx" }}
    ┌─┘
  ┌─┘
  ├─  0ms DEBUG biome_lsp::handlers::analysis Pull actions result: PullActionsResult { actions: [] }
  ├─  0ms DEBUG biome_lsp::handlers::analysis Suggested actions: 
  │ []
┌─┘

```

**Comment by rikusen0335** [comment]
> Removing the files within /Users/<UserName>/Library/Caches/dev.biomejs.biome as mentioned on ...
tried this way, still doesn't work :(

**Comment by ematipico** [comment]
Looks at his log:

> 0ms DEBUG biome_lsp::handlers::analysis Cursor range 1030..1030

When applying the code actions, the LSP receives a range, and in that range, there aren't code actions to apply. I am not sure why, but that's information that comes from the client, so VSCode.

**Comment by ematipico** [comment]
Try to add this line, let's see if it helps:

```diff
{
  "editor.defaultFormatter": "biomejs.biome",
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
+	"source.fixAll.biome": "explicit",
    "source.organizeImports.biome": "explicit"
  },
}
```

FYI, `"explicit"` is an option meant to control your client, so it's possible that there's something else that is modifying that value

**Comment by rikusen0335** [comment]
> FYI, "explicit" is an option meant to control your client, so it's possible that there's something else that is modifying that value

The line, which `"source.fixAll.biome": "explicit",` was already defined.
Tho tried to add `formatOnSave: true` make it work :(

```diff
{
  "[typescriptreact]": {
+   "editor.formatOnSave": true,
    "editor.defaultFormatter": "biomejs.biome"
  },
}
```

Thank you for your support :)

Note:
Something I tried with:
```json
{
  "editor.codeActionsOnSave": {
    "quickfix.biome": "always",
    "source.organizeImports.biome": "always"
  },
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  }
}

```

**Comment by mkvlrn** [comment]
Kind of off topic and a couple days too late but seeing all these configs around here I just though I'd share that this right here works so you don't have to add multiple lines with the same setting for each language:

```json
{
  "[json][javascript][javascriptreact][typescript][typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  }
}
```

**Comment by KyrieLii** [comment]
> Kind of off topic and a couple days too late but seeing all these configs around here I just though I'd share that this right here works so you don't have to add multiple lines with the same setting for each language:
> 
> ```json
> {
>   "[json][javascript][javascriptreact][typescript][typescriptreact]": {
>     "editor.defaultFormatter": "biomejs.biome"
>   }
> }
> ```

Thanks, It's work for me.
But why `{ "editor.defaultFormatter": "biomejs.biome",}` is not work, is it necessary to specify languages? 🤔

**Comment by ematipico** [comment]
It should, AFAIK. Maybe it's overridden by something else

**Comment by KyrieLii** [comment]
@ematipico I find it !
Because there is in settings.json：
```json
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```
BUT! cmd + , does not show this configuration 😭 
This should be a vscode bug.

**Comment by MaccKOT** [comment]
VS Code 1.95.2, extension: Biome v2.3.0
Same problem: format on save don't work entire for all type of files (even when I changed the default formatter) until I disabled the Biome extension.

**Comment by jovand3v** [comment]
If you've tried most of the things above and still no luck this should hopefully help you debug further:

`CTRL` + `SHIFT` + `P`
`Format Document` (in pop-up bar)
Select `Format Document`

It should raise a warning saying something like "Extension 'Biome' is configured as formatter but it cannot format etc etc", from there you should be able to debug your case yourself; in my case after restarting VSCode it automatically raised a warning that Biome wasn't installed properly

**Comment by MaccKOT** [comment]
> If you've tried most of the things above and still no luck this should hopefully help you debug further:
> 
> `CTRL` + `SHIFT` + `P` `Format Document` (in pop-up bar) Select `Format Document`
I did all of those things, as well as manually write the settings in json file. Then I started using Deno, and it already has its own formatter built in, but it also refused to format when saving the document, until I completely removed the Biome extension from VS Code.

**Comment by damianpumar** [comment]
Hello all!
Just in case I had the same issue and I noticed that the problem is in the biome.json 

Review your files prop in the json.
```
"files": {
    "include": ["./src/**/*"]
},
```

**Comment by hj5230** [comment]
I think I figured out why this is happening.
The issue lies in how language selectors are implemented differently between formatters:

Prettier's VSCode extension has special handling for comma-separated language selectors in settings.json, automatically splitting them into separate configurations internally. For example, this works with Prettier:

```json
"[typescript, typescriptreact, json]": {
  "editor.formatOnSave": true
}
```

However, Biome strictly follows VSCode's native language selector syntax, which requires separate configuration blocks for each language. The correct way for Biome would be:

```json
"[typescript]": {
  "editor.formatOnSave": true
},
"[typescriptreact]": {
  "editor.formatOnSave": true
},
"[json]": {
  "editor.formatOnSave": true
}
```

**Comment by massucattoj** [comment]
Thanks @hj5230 , I was stuck on that thing.. I used biome on nodejs and it's working fine if just 

`
  "editor.formatOnSave": true,
  "[typescript]": {
      "editor.defaultFormatter": "biomejs.biome"
  },

`
but now on React and Vite I need to specify like you said.

**Comment by Gorthog** [comment]
If you are experiencing 1-2 seconds delay when formatting a file, for me this was the culprit.
```
 "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit"
  }
```

**Comment by Christianj40** [comment]
I spent hours banging my head against the wall before realizing the my issue — my `/src` folder was listed in `.gitignore`, which is why my code wasn’t being formatted.

**Comment by vdawg-git** [comment]
For me it stopped working after upgrading from 1.8.x to `2.2.6`.
`Format document (forced)` does a format.
But just regular `Format document` wont even trigger a formatting event in the plugin output.

However I remember having that also with the old version, but it just started working again I think.

## Edit, How I fixed it
My global Biome version did not match with the version installed in my project. 
Uninstalling the global one fixed it. (The global one was installed through a nix dev)

**Comment by yacineahmaich** [comment]
It works for me after installing the biomejs vscode extension.
Now vscode can recognize the biome formatter.

<img width="632" height="159" alt="Image" src="https://github.com/user-attachments/assets/245dd0a8-1b4a-4408-8c14-5c86f1920c00" />

**Comment by wojtekKrol** [comment]
Those are the settings that worked for me :) after couple of hours of testing 
I put them into `.vscode/settings.json`

```
{
	"biome.enabled": true,
	"files.autoSave": "onFocusChange",
	"editor.formatOnSave": true,
	"files.autoSaveWorkspaceFilesOnly": true,
	"editor.defaultFormatter": "biomejs.biome",
	"editor.codeActionsOnSave": {
		"source.fixAll.biome": "always"
	}
}
```

**Comment by RemyMachado** [comment]
What worked for me, was having both:
- `"editor.defaultFormatter": "biomejs.biome"`
- `"editor.formatOnSave": true`

for each language:
```json
"editor.defaultFormatter": "biomejs.biome",
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit",
    "source.fixAll.biome": "explicit"
  },
```

---

To access this config file:
`Ctrl+Shift+P` _(to open the command pop-up)_
and type `Preferences: Open User Settings (JSON)`

---

Also sometimes a little `Ctrl+Shift+P` and typing `Biome: Restart` is enough.

**Comment by sanjaysah101** [comment]
Hi everyone,

After reading through the discussion and testing a few different setups, I found a configuration that consistently gets auto-formatting and "fix on save" working for me.

This setup explicitly defines Biome as the default formatter for relevant languages and ensures that conflicting extensions (like Prettier or ESLint) are disabled to prevent fighting over the file.

Here is the `.vscode/settings.json` configuration that worked:

Biome version: `2.3.14`

```jsonc
{
  "editor.defaultFormatter": "biomejs.biome",
  "editor.formatOnSaveMode": "file",
  "editor.codeActionsOnSave": {
    "source.organizeImports.biome": "explicit",
    "source.fixAll.biome": "explicit"
  },
  "editor.formatOnSave": true,
  "files.autoSave": "onFocusChange",

  // Explicitly set Biome as formatter for specific languages
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[json]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },
  "[jsonc]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.formatOnSave": true
  },

  // Disable Prettier & eslint extension if installed
  "prettier.enable": false,
  "eslint.enable": false,

  "files.associations": {  
    "*.css": "postcss"  // Fix tailwind import and unknown error
  },
  "typescript.tsdk": "node_modules\\typescript\\lib" // Use TS version defined in your package.json
}

```

Note: Don't forget Reload **Vs code** to apply these changes. 

Hope this helps others facing the same issue!
