### ISSUE TITLE
🐛 Biome doesn't ignore files if they have parse errors

### ISSUE THREAD

**Issue by kettei-sproutty** [biomejs/biome-vscode#239]
### VS Code version

1.90.1

### Extension version

2.3.0

### Biome version

1.8.1

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

Parse errors in `files.ignore` are ignored in `CLI` but not in extension.

Rage:
```
CLI:
  Version:                      1.8.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.8"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

Minimal reproducible example:
- Git: [https://github.com/kettei-sproutty/biome-parse-error-ignored/](https://github.com/kettei-sproutty/biome-parse-error-ignored/)

In my very use case, I'm working with .svx files (Svelte MDX) in VSCode, and I want to suppress errors indicating that I can't use <svelte:head> (as the image below, i have *.svx files associated with svelte in vscode).

<img width="191" alt="image" src="https://github.com/biomejs/biome/assets/65831826/ea223311-5fa3-48ec-beb4-c0854a5406b4">
<img width="883" alt="image" src="https://github.com/biomejs/biome/assets/65831826/de83f9cc-9794-4602-8524-678c4489d42b">

So I added `*.svx` files in the `files.ignored`, expecting errors to be suppressed, but nothing changes, errors still showing up.

In the CLI, files are correctly ignored.

Btw, thanks all for the great work you all are doing!

### Steps to reproduce

1. Add a file to biome `files.ignore`
2. Create a parse error in that file (in minimal reproducible, i used ts syntax in js file)

### Expected behavior

Ignored files shouldn't be checked by Biome LSP

### Does this issue occur when using the CLI directly?

No

**Comment by ematipico** [comment]
That's intended, because Biome wants to be a language server, so it provides parsing diagnostics, like typescript language server

**Comment by kettei-sproutty** [comment]
ops, in fact if I enable `checkJS` on the repo and ignore the file from the tsconfig, I still end up with a `TS Error` on the JS file with the types, sorry I hadn't even taken this into consideration.

Thank you! :)

**Comment by OliverJAsh** [comment]
Is there any way to configure the extension to ignore specific files?
