### ISSUE TITLE
🐛 Code is removed after formating on save

### ISSUE THREAD

**Issue by sylvainpolletvillard** [biomejs/biome-vscode#240]
### VS Code version

1.90.1

### Extension version

2.3.0

### Biome version

1.8.1

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

Formating on save removes parts of the code. The "Format document" does not cause the bug, nor the "Save without formating". Only the format on save causes the bug.

Here's a video demonstrating the problem:

https://github.com/biomejs/biome-vscode/assets/566536/3e78ce1e-8363-4973-86a7-13948ab420da

As shown in video, the if() block is deleted when saving the file, with Ctrl+S, Autosave or the action panel

I'm sure it's linked to Biome because it doesn't happen when Biome is disabled

### Steps to reproduce

Saving when format on save is active causes the bug. It happens on very specific parts of code, I noticed happening on various pieces of code. It's always a recently modified part of the code that is impacted. It may be related to code following a comment, but I'm not sure about that

### Expected behavior

Obviously formatting should not remove code

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
The Biome trace in Output is empty
```

**Comment by Sec-ant** [comment]
Possible duplicate of https://github.com/biomejs/biome/issues/2260

**Comment by sylvainpolletvillard** [comment]
I confirm it's the same bug, it's fixed after  changing Format On Save VS Code setting to "file" instead of "modificationIfavailable"
