### ISSUE TITLE
🐛 Extension fails to find biome executable on Windows

### ISSUE THREAD

**Issue by tylerbutler** [biomejs/biome-vscode#246]
### VS Code version

1.90.1

### Extension version

2.3.0

### Biome version

1.7.3

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

We have contributors that use Windows, Linux, and macOS with our monorepo. Windows users sometimes report that Biome's language server won't start and invariably the issue is it can't find the executable, or it finds the one that won't work on Windows (because Windows doesn't read/use shebangs) -- that is, `biome` instead of `biome.CMD`. The extensions `lspBin` setting would help, except it's not possible to set it in a cross-platform way in the VSCode workspace settings.

When Windows users set the lspBin to biome.CMD in their user settings, the extension is able to load it correctly. This is the CMD wrapper that npm creates on Windows automatically when installing deps with a bin field.

### Steps to reproduce

See description.

### Expected behavior

Ideally the extension would be able to find the correct executable per platform. Perhaps it isn't checking for the CMD wrapper on Windows? But even if that was resolved, it might be helpful to have a per-platform lsbBin setting. For example, `lspBinWindows`, `lspBinLinux`, etc. I don't care too much about the names or how they work, as long as there's a way to set an explicit path per platform. That way we could configure the workspace settings for everyone working in the repo regardless of platform.

### Does this issue occur when using the CLI directly?

No

**Comment by alexvy86** [comment]
As an add-on to @tylerbutler's suggestion, maybe something like `biome.lspBin.windows`, `biome.lspBin.linux`, etc, to align with what VSCode usually does:

![image](https://github.com/biomejs/biome-vscode/assets/716334/718f5fc8-0c27-45e7-bfd3-e47813181065)

**Comment by nhedger** [comment]
When the extension looks for biome in the project's dependencies, it does attempt to locate the platform specific executable.

When you install `@biomejs/biome`, it should trigger the installation of a `@biomejs/cli-[platform]-[arch]` package.

- What package manager do you use ?
- Can you find the `@biomejs/cli-win32-x64` package in your `node_modules` ?
- Could you please share the contents of VS Code's `OUTPUT` tab for `Biome` ? It should tell us how the extension attempts to resolve Biome.

**Comment by ematipico** [comment]
There's to note, that sometimes the package managers don't install **optionalDependencies** (due to some configuration/options).

**Comment by tylerbutler** [comment]
Thanks a lot for looking into this!

> When the extension looks for biome in the project's dependencies, it does attempt to locate the platform specific executable.
> 
> When you install `@biomejs/biome`, it should trigger the installation of a `@biomejs/cli-[platform]-[arch]` package.
> 
> * What package manager do you use ?
> * Can you find the `@biomejs/cli-win32-x64` package in your `node_modules` ?
> * Could you please share the contents of VS Code's `OUTPUT` tab for `Biome` ? It should tell us how the extension attempts to resolve Biome.

We use pnpm v8, and the per-platform packages are indeed installed in node_modules.

I should have mentioned that we set `biome.searchInPath` to `false`. We recently switched from prettier to biome, and the PR doing the switch was open for several months. We did initial testing with an earlier version of biome and the extension and setting it to false resolved something we noticed but I can't remember exactly what. But that may have been a mistake. Sorry I forgot to mention it earlier.

Anyway, we're only a couple of days into the switch and I think some of our problems may be on our side and will sort themselves out. I'll circle back early next week with some more details.

**Comment by tylerbutler** [comment]
OK, now that we're a couple of weeks into our transition, it seems that the problems have gone away, so I will close this issue. Thanks!

**Comment by vchirikov** [comment]
npm version: 10.8.1
vs code biome plugin: v2.3.0
@biomejs/biome: 1.8.3

settings.json:

```json
{
  "biome.lspBin": "code/nodejs/node_modules/.bin/biome",
}
```

> Can you find the @biomejs/cli-win32-x64 package in your node_modules ?

yes.

biome vscode logs:
```
Biome binary found at <workspacePath>\code\nodejs\node_modules\.bin\biome
Executing Biome from: <workspacePath>\code\nodejs\node_modules\.bin\biome
[Error - 1:19:51 PM] Biome client: couldn't create connection to server.
Error: spawn <workspacePath>\code\nodejs\node_modules\.bin\biome ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[cli-stdout] end
[cli-stderr] end
[cli-stdout] finish
[cli-stderr] finish
[cli-stderr] close
[cli] close -4058
[cli-stdout] close
```

On Windows where is no way to setup crossplatform `biome.lspBin` setting (I also tried `code/nodejs/node_modules/@biomejs/biome/bin/biome` with same result)

It works only if I use OS based path e.g. `code/nodejs/node_modules/.bin/biome.cmd`
I think the issue should be reopened.

cc: @ematipico , @nhedger

**Comment by ematipico** [comment]
I am not sure why. We document where the binaries are saved: https://biomejs.dev/guides/editors/create-a-plugin/#use-stdin

@vchirikov the path you're using **isn't** the binary, that's just a tiny shell that redirects to the correct binary based on OS and architecture.

**Comment by vchirikov** [comment]
@ematipico the issue:

the vscode workspace folder != folder with `package.json` (nodejs root of the project) => I must provide `biome.lspBin` (or use `PATH` variable which is not recommended, because I can have several projects with different biome versions). 
So, I must provide the path in `${workspaceFolder}/.vscode/settings.json` but I can't share the setting `"biome.lspBin": "code/nodejs/node_modules/@biomejs/cli-win32-x64/biome.exe",` because it won't work for linux/macos users (it will work only on win machines). I can't place this setting in git, because it's not cross-platform to point `.exe`.

**Comment by nhedger** [comment]
> @ematipico I will try to explain the issue:
> 
> the vscode workspace folder != folder with `package.json` (nodejs root of the project) => I must provide `biome.lspBin` (or use `PATH` variable which is not recommended, because I can have several projects with different biome versions). So, I must provide the path in `${workspaceFolder}/.vscode/settings.json` but I can't share the setting `"biome.lspBin": "code/nodejs/node_modules/@biomejs/cli-win32-x64/biome.exe",` because it won't work for linux/macos users (it will work only on win machines). I can't place this setting in git, because it's not cross-platform to point `.exe`.

We're aware of this issue, and this is something we're hoping to solve in the next major version of the extension by introducing platform specific bin path configuration, and also providing a way to specify custom "root folders".

**Comment by Novo1999** [comment]
I re-installed windows and was having this issue, after digging for 2 hours, I installed vc redist latest and it worked.
