### ISSUE TITLE
Extension 'Biome' is configured as formatter but it cannot format 'JavaScript'-Files

### ISSUE THREAD

**Issue by rottmann** [biomejs/biome-vscode#25]
When i click configure, no biome is in the list.

I created a fresh new example project:

Installed Biome v2.0.0 in VSCode.

Added settings.json

```json
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "editor.formatOnSave": true,
```

/example.code.workspace

```json
{
  "folders": [
    {
      "path": "biome-test"
    }
  ]
}
```

/biome-test/package.json
```json
{
  "name": "biome-test",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "@biomejs/biome": "^1.4.1"
  }
}
```

/biome-test/biome.json (from biome-hompeage

```
{
  "$schema": "https://biomejs.dev/schemas/1.4.0/schema.json",
  "organizeImports": {
    "enabled": false
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  }
}
```

/biome-test/index.js

```js
console.log("Hello World!") // without semicolon so `biome check index.js` errors in cli
```

Restart everything, vscode has no biome.

In command line i can execute:

```shell
cd biome-test
./node_modules/.bin/biome check index.js
```
It shows `Checked 1 file(s) in 1031µs Found 2 error(s)`

Adding /biome/test/biome.json

```json
  "javascript": {
    "formatter": {
      "semicolons": "asNeeded"
    }
  }
```

Re-run and it shows `Checked 1 file(s) in 932µs`

So biome cli works and uses biome.json.

But not in VSCode. Tried nightly too, the same, no biome detected.

VSCode 1.84.2
Biome v2.0.0
Node v18.19.0
Linux Mint 21.2 (Ubuntu jammy)

Let me know, if i can provide more informations.

**Comment by gabberr** [comment]
I had the same issue. The vscode did not recognize biome for the js/ts files.
It was a single vscode workspace, however I had the `biome.json` initially in a subfolder.


I solved it by first moving `biome.json` to the root folder. I think the extension looks it up from there. 
Then adjust the configuration  `.vscode/settings.json` :
```
  "biome.requireConfiguration": false,
  "biome.lspBin": "./biome-test/node_modules/@biomejs/biome/bin/biome",
```

**Comment by br14n-sol** [comment]
I have the same problem, in my case when opening vscode it seems to work perfectly, then randomly it tends to stop working for no apparent reason.

Checking the output window it seems that for some reason it does not find the configuration file (located in the root of the project) anymore:
```
Configuration file required, looking for one.
No config file found, disabling Biome extension
```
![image](https://github.com/biomejs/biome-vscode/assets/60621046/c979bd2a-b58f-40a8-8c8e-3add9e8e7413)

**Comment by taylor-lindores-reeves** [comment]
Same issue here - happens rather frequently, very frustrating.

<img width="307" alt="Screenshot 2023-12-15 at 17 32 45" src="https://github.com/biomejs/biome-vscode/assets/27443324/4a85ad50-ad5a-427d-b5e3-a832c5abed83">

**Comment by gabberr** [comment]
@nhedger I have created a reproduction repository https://github.com/gabberr/vscode-biome-issue/

**Comment by gabberr** [comment]
Updated the repo.
The settings for `biome.lspBin` work only without `{workspaceFolder}`.  https://code.visualstudio.com/docs/editor/variables-reference

**Comment by gabberr** [comment]
Moving biome.json to the root folder and then reloading the window, enables the squiggly lines:

![Screenshot 2023-12-19 at 16 57 56](https://github.com/biomejs/biome-vscode/assets/4170189/2fd86254-fc10-4422-9b01-73e929f79944)

**Comment by risu729** [comment]
I faced the same issue with this. I'm relly not sure, but I found docs about "formatting API."
https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_the-formatting-api
It seems this extension does not follow this, so it might be the cause of why the Biome extension is sometimes not registered as a formatter.

Additionally, [`prettier-vscode`](https://github.com/prettier/prettier-vscode) is successfully registered as a formatter of JavaScript files as this screenshot.
It prompts me to choose the default format of JavaScript files.
![image](https://github.com/biomejs/biome-vscode/assets/79110363/ca181e94-3bf1-41f4-801f-9bfaefa4b954)

`prettier-vscode` uses `registerDocumentFormattingEditProvider` API as below.
https://github.com/prettier/prettier-vscode/blob/70604a3d4ff5c0827339b6be6111e4abc38e2010/src/PrettierEditService.ts#L247

**Comment by jsejcksn** [comment]
I can reliably reproduce this with the following steps:

1. open a new editor tab and paste in some copied source code text (e.g. TypeScript)
2. verify that the [language mode](https://code.visualstudio.com/docs/languages/overview#_change-the-language-for-the-selected-file) of the editor is correct for the pasted content (e.g. TypeScript) — in the case that it wasn't correctly [auto-detected](https://code.visualstudio.com/updates/v1_60#_automatic-language-detection)
3. use the VS Code command "Format Document" from the command palette

It would be useful for Biome to be able to format the content of an editor which has never been saved (one which has no corresponding FS file — see example above).

It could do this by treating the content the same way it does `stdin` and use the editor's current [language mode](https://code.visualstudio.com/docs/languages/overview#_change-the-language-for-the-selected-file) to determine language.

In pseudo-code, the CLI operation that represents what I'm describing would be:

```sh
# FILE_EXT=<derived from editor language mode>
# e.g. ".ts"

# TEXT=<text content of editor>
# e.g. "function double(n: number): number { return n * 2 } const n = 5; double(5)"

printf $TEXT | biome format --stdin-file-path="file$FILE_EXT"
```

Which would result in:
```text
function double(n: number): number {
	return n * 2;
}
const n = 5;
double(5);

```

Let me know if it's determined that this is only tangentially related to this topic and deserves a separate issue.

**Comment by ematipico** [comment]
It seems to be that the original issue is due to the fact that the configuration file isn't placed at the root of the project.

@jsejcksn it seems that your issue is different, and it's related to the LSP itself, not the extension. I was sure we were able to handle unsaved files.

**Comment by jsejcksn** [comment]
> I was sure we were able to handle unsaved files.

@ematipico Are you suggesting that the steps I posted should result in a successful format instead of seeing the following error message?

> Extension 'Biome' is configured as formatter but it cannot format 'TypeScript'-files

If yes, should I open a separate issue in this repository with the content of my original comment?

**Comment by ematipico** [comment]
> > I was sure we were able to handle unsaved files.
> 
> @ematipico Are you suggesting that the steps I posted should result in a successful format instead of seeing the following error message?

Exactly 💯

> 
> > Extension 'Biome' is configured as formatter but it cannot format 'TypeScript'-files
> 
> If yes, should I open a separate issue in this repository with the content of my original comment?

Please open an issue in the main repository. Also, provide the daemon logs by using `biome rage --daemon-logs`.

It could be very long, so make sure to extract the logs emitted when attempt the formatting.

**Comment by jsejcksn** [comment]
> Please open an issue in the main repository. Also, provide the daemon logs by using `biome rage --daemon-logs`.
> 
> It could be very long, so make sure to extract the logs emitted when attempt the formatting.

@ematipico Done. There were no logs. 🤷

**Comment by gabberr** [comment]
Is there anything missing in the repro https://github.com/biomejs/biome-vscode/issues/25#issuecomment-1862517467 or something I can try/add to help out? The issue this has the `Needs reproduction` label.

**Comment by nhedger** [comment]
Hey @gabberr,

### What the extension expects

1. There is a `biome.json` file at the root of your repository (workspace), unless the `biome.requireConfiguration` is set to `false`
2. The `@biomejs/biome` package is installed in a `node_modules` folder at the root of your repository (or higher).

### Explanation

If (1) is not satisfied, the extension won't start, and you get the the following message when trying to format:

> Extension 'Biome' is configured as formatter but it cannot format 'JavaScript'-Files

If (2) is not satisfied, the extension will prompt you to download Biome, which you can accept or decline. If you choose to download Biome, the extension will use that downloaded binary instead of looking for the `@biomejs/biome` package in `node_modules`.

### Your reproduction

Your reproduction repository does not satisfy either at the moment:

1. The `biome.json` file is currently not at the root of your project, it is in the `frontend` subfolder.
2. The `@biomejs/biome` package is installed in a `node_modules` folder that is not at the root of your project, it is inside the `frontend` subfolder.

### Solutions

Here are a couple solutions:

1. If you want to keep the `@biomejs/biome` package installed in the `frontend` subfolder, you must specify the `biome.lspBin` (as you've done), but you must also move the `biome.json` file to the root of the project, otherwise it won't be picked up and the extension won't start.
2. Use NPM workspaces, and install `@biomejs/package` in the root npm workspace. You'll also need to move the `biome.json` file to the root of the project.

**Comment by gabberr** [comment]
Thank you for the explanation! My understanding is htat the requirement of th vscode extension is to have the `biome.json` defined in the root folder. 

I am thinking about how the biome works, as is described here.
https://biomejs.dev/guides/big-projects/

Does the extension support projects with multiple biome configurations?

If it does, could I create a `biome.json` file in the workspace root folder, which enables the formatter, linter, autoImport, to satisfy the requirement. Then in the `frontend` folder, the `biome.json` with the desired configuration would be defined.

I tried this approach in the repo. The extension started working but was using the biome setting from the root folder and not frontend folder.

**Comment by kasperstorgaard** [comment]
I had the same outcome as @gabberr when testing this out for our monorepo last week, and was confused, since the CI works great with that setup. (and you def. don't want a situation where editor and CI is out of sync)

**Comment by nhedger** [comment]
> Thank you for the explanation! My understanding now is that the requirement of the vscode extension is to have the `biome.json` defined in the root folder.
> 
> I am thinking about how the biome works, as is described here. [biomejs.dev/guides/big-projects](https://biomejs.dev/guides/big-projects/)
> 
> Does the extension support projects with multiple biome configurations?
> 
> If it does, could I create a `biome.json` file in the workspace root folder, which enables the formatter, linter, autoImport, to satisfy the requirement. Then in the `frontend` folder, the `biome.json` with the desired configuration would be defined.
> 
> I tried this approach in the repo. The extension started working but was using the biome setting from the root folder and not frontend folder.

The extension no longer requires the `biome.json` file to be present, but the root of the workspace is still the only place Biome will look for it. Placing a `biome.json` in a subfolder won't work unless you run the CLI directly inside that folder.

**Comment by AhmedBaset** [comment]
I'm still seeing this in `"@biomejs/biome": "^1.8.3"`. The config file is already on the root (not a monorepo) and `@biomejs/biome` is installed. 🤔

This snippet is from `.vscode/settings.json`:

```json
{
  // ...
  "editor.defaultFormatter": "biomejs.biome",
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  }
}
```

**Comment by taylor-lindores-reeves** [comment]
> I'm still seeing this in `"@biomejs/biome": "^1.8.3"`. The config file is already on the root (not a monorepo) and `@biomejs/biome` is installed. 🤔
> 
> 
> 
> This snippet is from `.vscode/settings.json`:
> 
> 
> 
> ```json
> 
> {
> 
>   // ...
> 
>   "editor.defaultFormatter": "biomejs.biome",
> 
>   "[typescript]": {
> 
>     "editor.defaultFormatter": "biomejs.biome"
> 
>   },
> 
>   "[typescriptreact]": {
> 
>     "editor.defaultFormatter": "biomejs.biome"
> 
>   }
> 
> }
> 
> ```

What is the version in the config file set to?

**Comment by AhmedBaset** [comment]
> What is the version in the config file set to?

Which config?

**Comment by taylor-lindores-reeves** [comment]
> > What is the version in the config file set to?
> 
> 
> 
> Which config?

The biome.json file. I usually get this error when the extension version is out of sync with the config file

**Comment by AhmedBaset** [comment]
> > > What is the version in the config file set to?
> > 
> > 
> > Which config?
> 
> The biome.json file. I usually get this error when the extension version is out of sync with the config file

AFAIK, there is no version in biome.json

**Comment by DavidMelnychuk** [comment]
Any update on this? Using biome `1.8.3` and one day this seemed to randomly occur and I'm no longer able to format any of my files. Have `biome.json` in the root of the monorepo.

**Comment by taylor-lindores-reeves** [comment]
> Any update on this? Using biome `1.8.3` and one day this seemed to randomly occur and I'm no longer able to format any of my files. Have `biome.json` in the root of the monorepo.

Let's see your biome.json file?

**Comment by ematipico** [comment]
@DavidMelnychuk please create a new issue with a new reproduction

**Comment by leognmotta** [comment]
well, seems like setting eslint and prettier for my monorepo is much easier, thanks

**Comment by bledar** [comment]
I was able to resolve this issue by deleting the cached file on my system folders and reinstalling the Biome extension on VS Code.
- `cd ~/Library/Caches`
- `rm -rf dev.biomejs.biome/`
- Open VS Code
- Uninstall Biome
- Install Biome
- Reload VS Code

**Comment by alexkreidler** [comment]
I'm still getting this issue even though I have `biome.json` in the root of my project and I've installed `@biomejs/biome` globally.

**Comment by HMothaffar** [comment]
This issue should not be closed. I have `biome.json` in the root of my project and it's not working

**Comment by minhnguyenduy99** [comment]
I was able to resolve this by adding `.tsx` and `.ts` file in `files.include` options like following:
```json
{
  "files": {
    "include": ["src/**/*.ts", "src/**/*.tsx"],
    "ignoreUnknown": false,
    "ignore": []
  }
}
```

**Comment by mafiefa02** [comment]
> I was able to resolve this issue by deleting the cached file on my system folders and reinstalling the Biome extension on VS Code.
> 
> * `cd ~/Library/Caches`
> * `rm -rf dev.biomejs.biome/`
> * Open VS Code
> * Uninstall Biome
> * Install Biome
> * Reload VS Code

I can confirm this is working for me.

**Comment by peter-cognicode** [comment]
Tip to avoid duplication of the `biome.json`: create a symbolic link to the folder where you want it to live:

```
cd project
ln -s ./frontend/biome.json .
```

**Comment by tscanlin** [comment]
I had this issue and it was because I had multiple projects open and not all of them had a biome.json and from the logs it appeared to only be looking at the first project (alphabetized). I saw this in the logs here: `dev.biomejs.biome/`

To fix this I put my base settings at `Users/<my_user>/biome.json` since it seems to check there as well. Closing other projects may help too. Hope this helps someone else too.

**Comment by nojaf** [comment]
Setting `"biome.lspBin": "./frontend/node_modules/.bin/biome"` in my `.vscode/settings.json` and reloading the window worked for me.

**Comment by yazeryanski** [comment]
> I was able to resolve this issue by deleting the cached file on my system folders and reinstalling the Biome extension on VS Code.
> 
> * `cd ~/Library/Caches`
> * `rm -rf dev.biomejs.biome/`
> * Open VS Code
> * Uninstall Biome
> * Install Biome
> * Reload VS Code

Had the SAME issue now, with biome 1.9.4.
This solution helped me to fix it.

JFYI For the Windows, the cache folder is located at C:/Users/$your-user/AppData/Local/biomejs
Also, make sure that the biome.json is in the root folder of your vscode workspace.

**Comment by harrisrobin** [comment]
none of these solutions work for me on 1.9.4 :/

**Comment by daveycodez** [comment]
I'm having this issue trying to use Biome as the default formatter for JSON files and trying to edit the global VS Code settings.json

I assume Biome can't be used as a global formatter without workspace level biome.json?

**Comment by ShaneZhengNZ** [comment]
> > I was able to resolve this issue by deleting the cached file on my system folders and reinstalling the Biome extension on VS Code.
> > 
> > * `cd ~/Library/Caches`
> > * `rm -rf dev.biomejs.biome/`
> > * Open VS Code
> > * Uninstall Biome
> > * Install Biome
> > * Reload VS Code
> 
> Had the SAME issue now, with biome 1.9.4. This solution helped me to fix it.
> 
> JFYI For the Windows, the cache folder is located at C:/Users/$your-user/AppData/Local/biomejs Also, make sure that the biome.json is in the root folder of your vscode workspace.

I can confirm that following those steps fixed the issue for me. Thank you.

**Comment by olejorgenb** [comment]
Just chiming in that I'm, also facing this issue

**Comment by Rejke** [comment]
For WSL, you should try this:
```bash
rm -rf ~/.vscode-server/extensions/*
```
Replace `vscode` to `cursor` or `windsurf`, if you're using them

**Comment by gunn4r** [comment]
+1 Also having this issue all of a sudden. None of the possible solutions in this thread worked for me. (I'm on MacOS 14.1, running Biome 1.9.4.  This only started AFTER I updated biome to 1.9.4 from 1.9.2. Going back to 1.9.2 did not fix the issue for me unfortunately. Not sure whats up! Super annoying though!

**Comment by maxktz** [comment]
+1

**Comment by vladinator1000** [comment]
I followed the getting started instructions https://biomejs.dev/reference/vscode/#_top adding Biome to a fresh VSCode project and I'm also getting `FormattingExtension 'Biome' is configured as formatter but it cannot format 'JSON'-files`

**Comment by bulutfatih** [comment]
I have multiple projects, and not all of them use Biome. Since I installed Biome in one project, it somehow affects the others as well. Interestingly, when I use Prettier in a project, it works correctly except for `.ts` files.

I found this solution;

- Open the Command Palette(Ctrl/⌘+⇧+P) and select Preferences: Open User Settings (JSON)
- Find the following part
```
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
```
- Change it with Prettier
```
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```
- Save an close

Note: I am unsure why, but changing this setting through the GUI does not seem to work. Also why Biome changes user settings (not workplace setting) in the first place?? 😬

**Comment by wasimsandhu** [comment]
Tried all of the suggestions in this thread and nothing worked.

Then I tried to see if there was a way to install a different version of the extension. I started by installing a pre-release version (2025.5.40952), and boom, that's all I needed to do.

**Comment by samohovets** [comment]
I can still reproduce the issue on the latest version (`2025.5.251939`).

Can confirm that issue can be resolved by installing `2025.5.40952` version of the extension.

**Comment by d0z4rt** [comment]
> I can still reproduce the issue on the latest version (`2025.5.251939`).
> 
> Can confirm that issue can be resolved by installing version `2025.5.40952` of the extension.

Thank you for this, I've been trying to figure out why it wouldn't work for two hours....

Something weird I noticed, using the version `2025.5.251939` biome worked only for the file `.vscode/settings.json` but not `src/index.ts` or any other files (even `package.json`) and the LSP kept logging that it was formatting `.vscode/settings.json` even if I was editing another file.

**Comment by alex-rankin** [comment]
Had a similar issue, ended up being my user settings JSON in VSCode having the below set:

`"editor.defaultFormatter": "esbenp.prettier-vscode"`

Removed that, restarted, and all working - if that helps anyone else scratching their heads that has come from prettier :)

**Comment by arenclissold** [comment]
My issue was I had biome installed globally through npm with a project install as well. Switching to installing globally with brew and having a project install fixed the issue

**Comment by FDiskas** [comment]
In Vscode, near the terminal - check the Output TAB, filter Biome - and see errors. In my case, it was the  wrong schema version and some syntax

**Comment by mattpopovich** [comment]
> In Vscode, near the terminal - check the Output TAB, filter Biome - and see errors. In my case, it was the wrong schema version and some syntax

Thanks for this. My "Biome (dev container name)" output tab was telling me that it could not find the biome executable/binary: `[error] Unable to find the Biome binary.`

My fix was to install biome globally in my dev container's Dockerfile: `RUN npm install -g @biomejs/biome`.

Now my "Biome (dev container name)" output tab gives `[info]  ✅ Biome is ready.`.
