### ISSUE TITLE
Problems on linux (EACCES perms)🐛 

### ISSUE THREAD

**Issue by ThatGuyJamal** [biomejs/biome-vscode#256]
### VS Code version

1.90.2

### Extension version

2.3.0

### Biome version

1.8.3

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

The extension can't connect to the biome.js server. After googling a little I realized it might be a Linux permission thing. I am using pop-os Linux (ubuntu-based system) and Biome might be trying to access a network library that might be locked. Im not sure how to give an extension elevated permissions (or if I even should...). 

There's not much information I have on why the bug happened as it happens on install so I can't do any more testing as it does not even run. However, the logs did say the binary was found in the node_modules and running biome.js from the npm commands works as normal so I believe it's strictly an extension problem.

### Steps to reproduce

1. Install biome from vscode extensions store
2. Add `"biome.lspBin": "web/node_modules/@biomejs/biome",` to your vscode **settings.json** file. Im using a mono-repo so I added this path for where I needed biome in my project.

After these 2 steps the extension crashes completely with the error below.

### Expected behavior

The extension to start like normal...

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
Biome binary found at /home/thatguyjamal/.../web/node_modules/@biomejs/biome
Executing Biome from: /home/thatguyjamal/.../web/node_modules/@biomejs/biome
[Error - 12:29:34 AM] Biome client: couldn't create connection to server.
Error: spawn /home/thatguyjamal/.../web/node_modules/@biomejs/biome EACCES
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[cli-stdout] end
[cli-stdout] finish
[cli-stderr] end
[cli-stderr] finish
[cli-stderr] close
[cli] close -13
[cli-stdout] close
```

**Comment by ematipico** [comment]
That's not where the binaries are installed: https://biomejs.dev/guides/editors/create-a-plugin/#use-stdin (by the end of the chapter). The list is outdated, it doesn't list musl dists.

More here: https://www.npmjs.com/search?q=%40biomejs%2Fcli-
