### ISSUE TITLE
Extension does not start the server in offline environment

### ISSUE THREAD

**Issue by niklas-e** [biomejs/biome-vscode#26]
I installed the latest extension version (2.0.0) in an offline environment via `vsix`. The installation went fine, but the server doesn't start. Biome's status in status bar is stuck on initializing.

In biome extension's output I see it's using the local biome from node_modules

...but in Extension Host output there's an fetch error from the following stack trace (sorry, unable to provide the actual stack trace)

`activate -> statusBar.setUsingBundledBiome -> checkForUpdates -> getVersions`

I'd guess there's too eager update checking going on without proper error handling.

**Comment by nhedger** [comment]
Thanks for opening this issue @niklas-e.

The upcoming version of the extension will fix this issue.

**Comment by br14n-sol** [comment]
+1, I was about to open a new issue. 😆

**Comment by nhedger** [comment]
> +1, I was about to open a new issue. 😆

If you’re experiencing a similar issue on the latest version of the extension, please do open a new issue.

**Comment by br14n-sol** [comment]
> > +1, I was about to open a new issue. 😆
> 
> If you’re experiencing a similar issue on the latest version of the extension, please do open a new issue.

Isn't the latest version the same as the one with this problem (2.0.0)? Or has some other version been released and I haven't heard about it? 🫣

**Comment by nhedger** [comment]
Oh that's correct, my bad!

Will try to release a version some time next week, hopefully.

**Comment by br14n-sol** [comment]
> Oh that's correct, my bad!
> 
> Will try to release a version some time next week, hopefully.
> 
> In the meantime we could publish a new nightly if you want to try.

Sure, although I may try after the holidays 🎅, tomorrow the 25th or the 26th.
