### ISSUE TITLE
🐛 Biome is not recognized as a formatter for typescript 

### ISSUE THREAD

**Issue by uwehdaub** [biomejs/biome-vscode#293]
### VS Code version

Version: 1.91.1

### Extension version

2.3.0

### Biome version

1.8.3

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

Biome is not recognized as a formatter for typescript.
It is installed and even after a new start of vscode it is not recognized.
Maybe this is related to #238 

See the screenshot
![biome-not-found](https://github.com/user-attachments/assets/e638b662-310d-4c02-aad3-200c9dc948b1)

### Steps to reproduce

1. Create a empty profile in vscode
2. Install biome
3. deactivate the default typescript formatter in settings
4. --> format document (crtl-shift-I)
5. see the message

### Expected behavior

I want to use biome as typescript formatter.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by rootedsoftware** [comment]
I've created a reproduction here. 
https://github.com/Rooted-Software/biome-ts-error-reproduction

And here is what the error looks like in VSCode. 
<img width="525" alt="Code 2024-08-02 13 49 10" src="https://github.com/user-attachments/assets/4f605a92-8f63-4db1-ba4e-08e6fd518c7b">

**Comment by rootedsoftware** [comment]
I'm using MacOS, so it looks like the issue isn't related to the OS.

**Comment by nhedger** [comment]
> I've created a reproduction here. I used create-next-app and then added a biome.json file and saved as a new workspace, then copied my normal configuration over. https://github.com/Rooted-Software/biome-ts-error-reproduction
> 
> And here is what the error looks like in VSCode. <img alt="Code 2024-08-02 13 49 10" width="525" src="https://private-user-images.githubusercontent.com/3142974/354695299-4f605a92-8f63-4db1-ba4e-08e6fd518c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MzA1NDEsIm5iZiI6MTcyMjYzMDI0MSwicGF0aCI6Ii8zMTQyOTc0LzM1NDY5NTI5OS00ZjYwNWE5Mi04ZjYzLTRkYjEtYmE0ZS0wOGU2ZmQ1MThjN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMjAyNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZlZTEzMjZmMWI4NDBjYTg3ZmFjZTI5NTdlMzE3YzE5OTEzM2JiMmJlODM1ZGFiODVkYzJlZTY5NjY1YzU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CkrPYSPD1aonj_DW_t6xlidpF9SRhBWYzJeXs8oHfBE">

Thanks for the reproduction. Unfortunately, I cannot reproduce the issue.

I notice that you don't have `@biomejs/biome` in your `devDependencies`. 

- Are you using a global installation? 
  - If so, which version are you using?
- What does the Biome status bar say in VS Code when you open the tsx file?
- What the _output_ of the biome extension (see in output panel) ?

**Comment by rootedsoftware** [comment]
The issue did come down to the globally installed @biomejs/biome. I removed that global install and installed locally in my repo and now it works fine.

**Comment by uwehdaub** [comment]
@rootedsoftware Thanks for jumping in.
@nhedger Thanks for taking up this issue so quickly.
While trying to reproduce this problem in a dedicated repo I failed. 
So I will continue to find my error in my existing repo first.
