### ISSUE TITLE
Compatibility issue with yarn pnp

### ISSUE THREAD

**Issue by bazo** [biomejs/biome-vscode#31]
Hi,

we use yarn pnp in our project and the extension complains it cannot find the @biomejs/biome package
```
Could not find Biome in your dependencies. Either add the @biomejs/biome package to your dependencies, or download the Biome binary.
```

but @biomejs/biome is in the dev dependencies
```json
"devDependencies": {
    "@biomejs/biome": "1.4.1"
}
```

how can i make this combo work?
thanks

**Comment by ElGatoNinja** [comment]
hi @nhedger, It happens to us as well. But I come with a juicy repro :)

**Comment by nhedger** [comment]
Hey, just wanted to let you know I'm closing this issue in favor of the following task: https://github.com/biomejs/biome-vscode/issues/126.

Feel free to chime in if you'd like to help implement Yarn PnP support.
