### ISSUE TITLE
🐛 v3 prerelease: Biome won't start

### ISSUE THREAD

**Issue by ffMathy** [biomejs/biome-vscode#331]
### VS Code version

1.92.2

### Extension version

v2024.8.301002 (pre-release)

### Biome version

0.3.3

### Operating system

- [ ] Windows
- [X] macOS
- [X] Linux

### Description

Biome won't start.

### Steps to reproduce

Not sure about steps to reproduce yet, but I am running inside a DevContainer. The DevContainer is running a linux image, and the host is on Mac M1.

### Expected behavior

I expected Biome to start up and work.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

I do not see the "Biome Trace" category. I only see "Biome" there.

It shows this:

```plain text
2024-09-06 08:11:57.971 [info] Biome extension activated
2024-09-06 08:11:58.918 [error] Failed to start Biome extension
```

**Comment by Jagget** [comment]
https://github.com/biomejs/biome-vscode/issues/329 ? Same thing.

**Comment by ffMathy** [comment]
How is it the same thing? I'm receiving different things in my output window, right?

**Comment by Jagget** [comment]
<img width="419" alt="Screenshot 2024-09-05 at 10 31 07 AM" src="https://github.com/user-attachments/assets/48dac572-b4ce-452f-a41c-5da22d896a68">
There's more than 1 Biome log.

**Comment by ffMathy** [comment]
It's weird. I only see one. Called Biome.

**Comment by nhedger** [comment]
The extension spawns one session per project and one global session. The global session is named Biome LSP and the project sessions have the path of the project as a suffix

**Comment by ffMathy** [comment]
Not for me. Very weird. It seems it crashes before this?

**Comment by nhedger** [comment]
There was an issue where the extension attempted to create a global session before creating a project session. If that failed for some reason, the rest wouldn't work. I believe https://github.com/biomejs/biome-vscode/commit/899efe17d31f7dc9866d9bb8ace13b7d64d03318 fixes that. Would you mind trying the latest pre-release (v2024.9.91939)?

I'll close in the meantime, but feel free to circle back if it does not fix the issue.
