### ISSUE TITLE
🐛 Cannot find installed biome binary

### ISSUE THREAD

**Issue by slhck** [biomejs/biome-vscode#337]
### VS Code version

1.91.1

### Extension version

v2024.8.301002

### Biome version

1.8.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

<img width="483" alt="SCR-20240909-jquh" src="https://github.com/user-attachments/assets/c642b845-61b9-4c77-8b82-5f92b9fb2986">

<img width="373" alt="SCR-20240909-jqvm" src="https://github.com/user-attachments/assets/7e562443-c2e3-4d75-8f27-9c9ca9da0fa3">

### Steps to reproduce

I simply added this:

```
yarn add --dev @biomejs/biome
npx biome init
```

I also installed the prerelease version of this extension.

### Expected behavior

Biome binary from node modules should be found.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
2024-09-09 10:31:51.668 [info] Biome extension activated
2024-09-09 10:32:54.370 [error] Failed to start Biome extension
2024-09-09 10:32:54.370 [info] Biome extension started
2024-09-09 10:32:54.370 [info] User-facing commands registered
2024-09-09 10:32:54.370 [info] Started listening for lockfile changes
2024-09-09 10:32:54.370 [info] Started listening for configuration changes
2024-09-09 10:32:54.370 [info] Started listening for active text editor changes
2024-09-09 10:32:57.702 [info] 





2024-09-09 10:32:57.702 [info] Biome extension activated
```

**Comment by slhck** [comment]
PS: This works when using the stable version of the extension.

**Comment by nhedger** [comment]
There was an issue where the extension attempted to create a global session before creating a project session. If that failed for some reason, the rest wouldn't work. I believe 899efe17d31f7dc9866d9bb8ace13b7d64d03318 fixes that. Would you mind trying the latest pre-release (v2024.9.91939)?

I'll close in the meantime, but feel free to circle back if it does not fix the issue.

**Comment by slhck** [comment]
This seems to work, thanks!

**Comment by u007** [comment]
guys, really appreacite the work,
but this is getting so frequent, perhaps you can just release the fix not under pre-release

**Comment by nhedger** [comment]
We released v3. If it doesn't fix it for you, please open a fresh issue with a reproduction repository

**Comment by haris-conga** [comment]
<img width="702" alt="Image" src="https://github.com/user-attachments/assets/77357a31-9aeb-471a-8d33-2c9c502d7a8a" />

<img width="1716" alt="Image" src="https://github.com/user-attachments/assets/936020cc-3411-4c8c-9710-ae4edfae3979" />

@nhedger I am still facing this problem on `3.0.3`

However when I do `biome rage`

```
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.17.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

**Comment by eliezra236** [comment]
I managed to fix it by installing biome as global package on windows 11
`npm i -g @biomejs/biome`

**Comment by FinzyPHINZY** [comment]
> I managed to fix it by installing biome as global package on windows 11 `npm i -g @biomejs/biome`

thanks for this @eliezra236 . it worked for me on linux too

**Comment by xremming** [comment]
I'm having this same issue under WSL with biome being installed with pnpm. It doesn't help to install biome globally either (and that's not really a fix either).

**Comment by vmpikaso** [comment]
I use M1 chip and I managed to fix it by installing biome cli in my project
`pnpm i -D @biomejs/cli-darwin-arm64@1.9.4`
By default when i use `pnpm i @biomejs/biome`, it will install @biomejs/cli-darwin-x64 as cli instead of `@biomejs/cli-darwin-arm64`

**Comment by heliomarpm** [comment]
> I'm having this same issue under WSL with biome being installed with pnpm. It doesn't help to install biome globally either (and that's not really a fix either).

the same here, using win11 and npm, global installation did not solve it.

besides that I am getting this error when trying to run the check.

```json
"devDependencies": {
"@biomejs/biome": "^2.0.2",
```

```bash
> biome check --write ./src

C:/Program Files/nodejs/node.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by gethari** [comment]
> I use M1 chip and I managed to fix it by installing biome cli in my project `pnpm i -D @biomejs/cli-darwin-arm64@1.9.4` By default when i use `pnpm i @biomejs/biome`, it will install @biomejs/cli-darwin-x64 as cli instead of `@biomejs/cli-darwin-arm64`

This worked for me, I have the same M1 MBP

**Comment by FinzyPHINZY** [comment]
> > I'm having this same issue under WSL with biome being installed with pnpm. It doesn't help to install biome globally either (and that's not really a fix either).
> 
> the same here, using win11 and npm, global installation did not solve it.
> 
> besides that I am getting this error when trying to run the check.
> 
> ```json
> "devDependencies": {
> "@biomejs/biome": "^2.0.2",
> ```
> 
> ```bash
> > biome check --write ./src
> 
> C:/Program Files/nodejs/node.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
> ```

Update to v3

**Comment by u007** [comment]
how to install v3?

**Comment by stefanbartos** [comment]
I had the same problem with Mac M1. I am using fnm to manage node env, and I didn't want to install it globally. I set the path manually in VSCode settings. I hope it helps.

.vscode/settings.json
```json
{
    "biome.lsp.bin": "node_modules/@biomejs/cli-darwin-x64/biome"
}
```

<img width="472" alt="Image" src="https://github.com/user-attachments/assets/5ae59f8f-ced8-4c3b-a360-6eb8e2ea5c77" />

**Comment by evanheckert** [comment]
> I had the same problem with Mac M1. I am using fnm to manage node env, and I didn't want to install it globally. I set the path manually in VSCode settings. I hope it helps.
> 
> .vscode/settings.json
> 
> {
>     "biome.lsp.bin": "node_modules/@biomejs/cli-darwin-x64/biome"
> }

If you're on an M1 mac, shouldn't it be `node_modules/@biomejs/cli-darwin-arm64/biome`? It is on my M2 Max MBP.

In any case, adding the path in settings as recommended in your post fixed the issue for me! Thanks!

Edit: No it did not fix it. The logs changed but still ended up with "cannot find installed biome binary". 

Final fix was `brew install biome`

**Comment by vladinator1000** [comment]
For me, updating to biome v2.0.6 and restarting VSCode worked on Windows + WSL.

**Comment by Itz-Agasta** [comment]
> For me, updating to biome v2.0.6 and restarting VSCode worked on Windows + WSL.

Yep, it worked for me too! In one of my repos, the older v2.0.0 wasn't working......updated to the latest version and boom, the extension started working perfectly.

**Comment by Bitnagar** [comment]
> <img alt="Image" width="702" src="https://private-user-images.githubusercontent.com/155518983/451855388-77357a31-9aeb-471a-8d33-2c9c502d7a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIzMDQ5OTIsIm5iZiI6MTc1MjMwNDY5MiwicGF0aCI6Ii8xNTU1MTg5ODMvNDUxODU1Mzg4LTc3MzU3YTMxLTlhZWItNDcxYS04ZDMzLTJjOWM1MDJkN2E4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxMlQwNzE4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzVhYjhmYmNmMGJiZmE4MGEyOTg0NjZmZGRiMmE5ODgwNWI3ZmUyMDM4NDlkZjA3MmMwYjI1M2FlZjg1NmNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7bMWJbNXx4l4R5PrAPNpnR9mc0_YUxMhShnvW98AyvY"> <img alt="Image" width="1716" src="https://private-user-images.githubusercontent.com/155518983/451855559-936020cc-3411-4c8c-9710-ae4edfae3979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIzMDQ5OTIsIm5iZiI6MTc1MjMwNDY5MiwicGF0aCI6Ii8xNTU1MTg5ODMvNDUxODU1NTU5LTkzNjAyMGNjLTM0MTEtNGM4Yy05NzEwLWFlNGVkZmFlMzk3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxMlQwNzE4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjc4YTMxZThkMmQ3YmU2ZjI5NDE3MWQxMjk2OGZlZGFjMjJhMzdiYjBiZThkYmIwOWU1M2YxN2I4Y2VhOTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TF0m1O_Vu2lAoxDtygLuV4TmyDhZtP0eFss7Hf1T7SU">
> [@nhedger](https://github.com/nhedger) I am still facing this problem on `3.0.3`
> 
> However when I do `biome rage`
> 
> ```
> CLI:
>   Version:                      1.9.4
>   Color support:                true
> 
> Platform:
>   CPU Architecture:             aarch64
>   OS:                           macos
> 
> Environment:
>   BIOME_LOG_PATH:               unset
>   BIOME_LOG_PREFIX_NAME:        unset
>   BIOME_CONFIG_PATH:            unset
>   NO_COLOR:                     unset
>   TERM:                         "xterm-256color"
>   JS_RUNTIME_VERSION:           "v20.17.0"
>   JS_RUNTIME_NAME:              "node"
>   NODE_PACKAGE_MANAGER:         unset
> 
> Biome Configuration:
>   Status:                       Loaded successfully
>   Formatter disabled:           false
>   Linter disabled:              false
>   Organize imports disabled:    false
>   VCS disabled:                 true
> 
> Workspace:
>   Open Documents:               0
> ```

Had the same issue. After following the docs, i restarted VS code, and it worked.

**Comment by Novo1999** [comment]
I re-installed windows and was having this issue, after digging for 2 hours, I installed vc redist latest and it worked.

**Comment by jakub-msqt** [comment]
Biome is working fine when running npm scripts. The extension can't find the binary. Is it because biome is not configured at the root of monorepo but rather for a specific app? I thought this should be supported.

**Comment by Alluseri** [comment]
```
2026-01-01 19:43:36.497 [warning] 🔍 Could not find global Node Modules path for npm
2026-01-01 19:43:36.569 [error] Unable to find the Biome binary.
```
Even though I can access `biome` from cmd just fine.

**EDIT:** I ended up just hardcoding the path into `npmGlobalNodeModulesPath`, it works now. Goofy but oh well.

**Comment by robert-barahona** [comment]
I have biome installed in the path `packages/biome-config` so I updated my .vscode/settings.json with:

```json
{
  "biome.lsp.bin": "./packages/biome-config/node_modules/@biomejs/biome/bin/biome"
}
```

And that worked for me
