### ISSUE TITLE
🐛 VS code complain/warns about lock of biome installed in a project that doesn't use biome

### ISSUE THREAD

**Issue by peterbe** [biomejs/biome-vscode#339]
### VS Code version

1.93.0

### Extension version

v2.3.0

### Biome version

n/a

### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux

### Description

I love biome and I use it in all new projects. So much faster than prettier. 
The problem is that it complains that I don't have biome installed. Can it not know that my the fact that the currently opened project does *not* have a `biome.json` file?

![Warning toast](https://github.com/user-attachments/assets/84cafa6b-1c04-4632-a03b-204ee4f01431)

### Steps to reproduce

1. Fresh new JS project (e.g. `npx create-next-app@latest && cd my-app`
2. Start vs code in the new JS project (e.g. `code .`)

### Expected behavior

No warning. 

### Does this issue occur when using the CLI directly?

No

**Comment by nhedger** [comment]
Hey, thanks for opening this issue. Actually, the upcoming version of the extension solves this problem by introducing the `biome.requireConfigFile` setting which will prevent the extension from starting in projects that do not have a `biome.{json,jsonc}` file.

You can try this today by switching to the pre-release channel of the extension within VS Code.

**Comment by mkvlrn** [comment]
I just keep `"biome.enabled": false` in my user settings and add `"biome.enabled": true` to `.vscode/settings.json` in the workspace where I use it.

The upcoming `biome.requireConfigFile` will be very much appreciated though!
