### ISSUE TITLE
🐛 Inappropriate link in README.md

### ISSUE THREAD

**Issue by nekoya** [biomejs/biome-vscode#344]
### VS Code version

none

### Extension version

none

### Biome version

none

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Description

I found an inappropriate link in README.md.

The link to the "official website" should definitely be fixed.

https://github.com/biomejs/biome-vscode/blob/6e8c0c93238a99432d168dcb07b1b8c764c02ffe/README.md?plain=1#L25

### Steps to reproduce

Open the link.

### Expected behavior

Move to an official website https://biomejs.dev/

### Does this issue occur when using the CLI directly?

No

**Comment by nhedger** [comment]
Good catch, thanks! Fixed in 75ad7ac
