### ISSUE TITLE
🐛  Biome simply doesn't work on vscodium

### ISSUE THREAD

**Issue by shellheim** [biomejs/biome-vscode#354]
### VS Code version

v1.93.1

### Extension version

v2.3.0

### Biome version

v1.9.1

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

When I open the linked repo, the  biome extension gives two notifications to report errors and then shuts down.

### Steps to reproduce

1. Install the biome extension and donwload the binary when prompted.
2. Open the repo in vscode/vscodium, observe the errors being thrown in the notifications.
   a. `Sending document notification textDocument/didOpen failed`
   b. `Client Biome: connection to server is erroring. Shutting down server.`

### Expected behavior

The extension simply works.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Link to a minimal reproduction

https://github.com/shellheim/biome-minimal

### Logs

```plain text
Couldn't find any trace logs in the biome trace category, but here's the biome category logs that I think are relevant.

Could not resolve Biome in the dependencies of workspace folder: /home/shell/Code/projects/react/repo
Searching for Biome in PATH
Biome binary found at /home/shell/.config/VSCodium/User/globalStorage/biomejs.biome/server/biome
Executing Biome from: /home/shell/.config/VSCodium/User/globalStorage/biomejs.biome/server/biome
[cli-stdout] data 44
[cli] exit 0
Connecting to "/home/shell/.cache/biome/biome-socket-1.9.1" ...
[cli-stderr] data 393
[Error - 15:41:25] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at Socket.writeAfterFIN [as write] (node:net:561:14)
	at /home/shell/.vscode-oss/extensions/biomejs.biome-2.3.0-universal/out/main.js:3008:25
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/shell/.vscode-oss/extensions/biomejs.biome-2.3.0-universal/out/main.js:2999:16)
	at StreamMessageWriter.doWrite (/home/shell/.vscode-oss/extensions/biomejs.biome-2.3.0-universal/out/main.js:1429:31)
	at /home/shell/.vscode-oss/extensions/biomejs.biome-2.3.0-universal/out/main.js:1420:25
[Info  - 15:41:25] Connection to server got closed. Server will restart.
true
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stdout] data 44
[cli] exit 0
Connecting to "/home/shell/.cache/biome/biome-socket-1.9.1" ...
[cli-stderr] data 393
[Error - 15:41:26] Client Biome: connection to server is erroring. Shutting down server.
[Error - 15:41:26] Client Biome: connection to server is erroring. Shutting down server.
[Error - 15:41:26] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 15:41:26] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 15:41:26] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
```

**Comment by nhedger** [comment]
Hey, any chance you could try with the prerelease of the extension. We've addressed a lot of issues since.

**Comment by shellheim** [comment]
Tried with the nightly, getting the same errors.

![biome](https://github.com/user-attachments/assets/6fdfea09-6334-4923-bbd4-626d334f1476)

**Comment by nhedger** [comment]
Looks like you've installed the deprecated nightly distribution. I'm talking about the pre-release channel on the extension. You can switch the channel on the extensions page within VS code

**Comment by shellheim** [comment]
Oh sorry, I fixed that. While the extension doesn't error out, it only works when I add `@biomejs/biome` as a dependency in my project. Is the sole binary option being phased out?

**Comment by shellheim** [comment]
Okay, so I just discovered this, formatting seems to be broken too. Though it lints fine.

**Comment by nhedger** [comment]
We're encouraging the use of the binayry through your dependencies, but if you install Biome globally on your system (in your PATH), we'll pick it up there if it cannot be found in your deps.

Alternatively, you can force the extension to use the binary of your choice by setting its path in `biome.lsp.bin`

**Comment by shellheim** [comment]
Ahh, thanks for the reply. Everything works as expected after adding the dep and tweaking some settings. Closing this now.
