### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by FlatMapIO** [biomejs/biome-vscode#36]
It looks like we should be able to limit the extensions to work only in workspace

```
[Error - 19:26:08] Request textDocument/codeAction failed.
  Message: Size of /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts is 1.2 MiB which exceeds configured maximum of 1.0 MiB for this project. The file size limit exists to prevent us inadvertently slowing down and loading large files that we shouldn't.
  Code: -32603 
```

<img width="1461" alt="image" src="https://github.com/biomejs/biome-vscode/assets/1720349/2d44c1bd-ca88-4c93-b1a7-afcd776af019">

**Comment by ematipico** [comment]
Hi @FlatMapIO 

You can lift the size limit by creating a configuration file and using this option: https://biomejs.dev/reference/configuration/#filesmaxsize

**Comment by FlatMapIO** [comment]
@ematipico Thank you for your reply. I've learned a lot.
