### ISSUE TITLE
🐛 Biome is not recognized as a formatter for GraphQL

### ISSUE THREAD

**Issue by caolrd8** [biomejs/biome-vscode#378]
### VS Code version

1.93.1

### Extension version

2.3.0

### Biome version

1.9.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

The Biome extension is not registered as a GraphQL formatter, even though the CLI formats the files just fine.

![image](https://github.com/user-attachments/assets/42499788-ef67-4c24-bb0a-535a1cc22f13)

### Steps to reproduce

1. Create a new project
2. Install @biomejs/biome and the extension
3. Create a GraphQL file
4. Run "Format document"
5. Observe the "There is no formatter for 'graphql' files installed" popup

### Expected behavior

I expect Biome to be registered as a GraphQL formatter, as the CLI supports formatting the files.

### Does this issue occur when using the CLI directly?

No

### Link to a minimal reproduction

https://github.com/caolrd8/biome-repro-1728040813273/tree/main

**Comment by ematipico** [comment]
This is fixed in the preview release. Can you confirm that?
