### ISSUE TITLE
No find a way to uninstall downloaded BiomejS binary in vscode

### ISSUE THREAD

**Issue by ginkishi** [biomejs/biome-vscode#394]
Hello,
After downloading and installing the biomejs binary with the help of vscode. 
Subsequently, I have not found a way to remove this binary in vscode's interface or through a terminal. 
Is there a way to do this?

![image](https://github.com/user-attachments/assets/0d7b3ed0-4135-4803-880b-6ed7c73cb927)
![image](https://github.com/user-attachments/assets/9b4b80ca-cd7d-4a68-adad-47aecc67a0ac)

**Comment by nhedger** [comment]
The current stable version doesn't provide a way to do it from VS Code.

You'll need to delete the files manually.

### Global storage

Delete the folder matching your OS:

- Linux: `~/.config/Code/User/globalStorage/biomejs.biome`
- macOS: `~/Library/Application\ Support/Code/User/globalStorage/biomejs.biome`
- Windows: `C:\Users\[User]\AppData\Roaming\Code\User\globalStorage\biomejs.biome`

### Workspace storage

Find all workspaces that have a biome binary downloaded

```
find ~/Library/Application\ Support/Code/User/workspaceStorage -name "biome"
```

And delete those folders.
