### ISSUE TITLE
🐛 Add command `Fix all auto-fixable problems` like eslint

### ISSUE THREAD

**Issue by axetroy** [biomejs/biome-vscode#402]
### VS Code version

1.94.2

### Extension version

2.3.0

### Biome version

1.9.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

As the title describes

### Steps to reproduce

None

### Expected behavior

None

### Does this issue occur when using the CLI directly?

No

**Comment by ematipico** [comment]
Please open a discussion
