### ISSUE TITLE
🐛 Allow workspace-relative paths for `biome.lsp.bin`

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [biomejs/biome-vscode#420]
### VS Code version

1.93.1

### Extension version

2024.10.131712

### Biome version

1.9.4

### Operating system

- [ ] Windows
- [ ] macOS
- [X] Linux

### Description

The old `biome.lspBin` setting in 2.3.x supported workspace-relative paths, while Biome 3.x (both for the new `biome.lsp.bin` setting and for the old `biome.lspBin` setting) only supports absolute paths. 

### Steps to reproduce

```jsonc
// <workspace>/.vscode/settings.json
{
  "biome.lsp.bin": "app/node_modules/.bin/biome"
}
```

```jsonc
// <workspace>/app/package.json
{
  "devDependencies": {
    "@biomejs/biome": "1.9.4"
  },
  "type": "module"
}
```

### Expected behavior

There should be a package-manager-independent way to reference a workspace-relative biome installation, either by supporting relative paths like `app/node_modules/.bin/biome` (as it was implemented in 2.x) or by allowing the use of placeholders as in `${workspaceFolder}/app/node_modules/.bin/biome`.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
2024-11-07 15:11:12.984 [info] 
...
2024-11-07 15:11:12.984 [info] Biome extension 2024.10.131712 activated
2024-11-07 15:11:16.690 [error] Could not find the Biome binary
```

**Comment by nhedger** [comment]
Thanks for opening this issue, I agree with you.

I'd accept a PR for this if you're up to the challenge, otherwise, we'll somehow get it done before releasing the stable version.

**Comment by AshutoshNanaware** [comment]
Hey , I will look into this and try fix this.
