### ISSUE TITLE
🐛 Javascript files showing Linter errors but not Formatter errors.

### ISSUE THREAD

**Issue by eslachance** [biomejs/biome-vscode#422]
### VS Code version

1.94.2

### Extension version

2.3.0

### Biome version

1.9.4

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

I am trying to use biome to replace eslint+prettier, but there's one blocker that's really causing issues. It seems that all the options under the the `linter` section are properly applied, but nothing in the `formatter` or `formatter/javascript` section are actually shown as errors in VSCode. 

If I actually run formatting using *Format Selection* or *Format Document*, it does indeed apply my preferences, like adding a missing semicolon and fixing indentation, but I don't want to have to do that all the time, I want to actually *see* my preferences. 

Interestingly, it has no problem with syntax errors (unexpected tokens, can't reassign to a constant, etc), so it's clearly running the parser on the file. But it's just seemingly ignoring all my formatter options.

![image](https://github.com/user-attachments/assets/71626d2d-7f7a-49c4-8ecf-6646915f7f7d)

### Steps to reproduce

1. Clone repo
2. open in vscode
3. npm install
4. open index.js
5. notice the glorious lack of any sort of warning, error, or indication of code problems except the `let` at the top.

### Expected behavior

Underline red squiggly lines are shown when code does not match selected formatter options or has common errors.

### Does this issue occur when using the CLI directly?

No

### Link to a minimal reproduction

https://github.com/eslachance/biome-repro-1731204392101

**Comment by ematipico** [comment]
This isn't a bug. This works as expected. Here's an explanation about it: https://github.com/biomejs/biome/discussions/809#discussioncomment-11038068

**Comment by eslachance** [comment]
Oh. Well that's sad, and it makes biomejs **not** a good fit to replace eslint, at all, whatsoever. I'm sad to see that you're actually not that helpful or a good replacement. Good luck with the project though, I guess.
