### ISSUE TITLE
Format Document command doesn't organize imports with Biome extension

### ISSUE THREAD

**Issue by batuhanoztrk** [biomejs/biome-vscode#425]
### Discussed in https://github.com/biomejs/biome-vscode/discussions/424

<div type='discussions-op-text'>

<sup>Originally posted by **batuhanoztrk** November 13, 2024</sup>
When using the Biome pre-release extension in VSCode, the "Format Document" command (`Ctrl/Cmd + Shift + P` > "Format Document" or `Alt + Shift + F`) doesn't organize imports automatically, even though organize imports is enabled in the Biome configuration.

### Environment
- VSCode Version: 1.93.1
- Biome Extension Version: 2024.10.131712 (pre-release)
- OS: Mac OS 15.1 (24B83)

### Configuration
My VSCode settings (`settings.json`):
~~~json
{
  "editor.accessibilitySupport": "off",
  "editor.unicodeHighlight.nonBasicASCII": false,
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1",
    "Q_NEW_SESSION": "1"
  },
  "workbench.colorTheme": "One Dark Pro Darker",
  "workbench.iconTheme": "a-file-icon-vscode",
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.wordWrap": "on",
  "editor.fontSize": 13,
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "files.autoSave": "afterDelay",
  "editor.formatOnType": true,
  "editor.formatOnPaste": true,
  "[json]": {
    "editor.defaultFormatter": "biomejs.biome",
  },
  "kotlin.languageServer.enabled": false,
  "kotlin.debugAdapter.enabled": false,
  "javascript.preferences.jsxAttributeCompletionStyle": "braces",
  "typescript.preferences.jsxAttributeCompletionStyle": "braces",
  "redhat.telemetry.enabled": true,
  "[dart]": {
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.rulers": [80],
    "editor.selectionHighlight": false,
    "editor.tabCompletion": "onlySnippets",
    "editor.wordBasedSuggestions": "off"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit"
  },
}
~~~

### Expected Behavior
When using the "Format Document" command, it should both format the code and organize imports.

### Actual Behavior
The "Format Document" command only formats the code but doesn't organize imports. I need to run the "Organize Imports" command separately.

### Additional Information
- The formatting itself works correctly
- Organize Imports works when run as a separate command
- This issue occurs specifically with the pre-release version of the extension

### Steps to Reproduce
1. Install Biome pre-release extension
2. Configure VSCode and Biome as shown above
3. Open a JavaScript/TypeScript file with unorganized imports
4. Run the "Format Document" command
5. Observe that imports remain unorganized</div>

**Comment by nhedger** [comment]
Import sorting is not part of the formatted, but the analyzer.

You can configure VS Code to trigger import sorting on save using the following config.

```json
{
  "editor.codeActionsOnSave":{
    "source.organizeImports.biome": "explicit"
  }
}
```

See https://biomejs.dev/reference/vscode/#imports-sorting-experimental

**Comment by khanakia** [comment]
@nhedger I am migrating from eslint and eslint does works `eslint lint --fix` and properly sort the packages

how do i sort the hundreds of files that's not possible sorting manually

**Comment by Gibitop** [comment]
I don't want to save the file to format the file or organize imports, because it triggers the build system to rebuild the project, but I want to be able to format the file I'm working on and organize imports with one shortcut

**Comment by plutack** [comment]
I am also having this problem particularly with helix ... I am fine with having the format on save also run the  organize imports. right now, I have to consciously trigger the  code action manually... if the linter is going to complain.. might as well have an easy way to fix this. 
The docs specify including some settings for other editors in the biome.json but that doesn't seem to work for me. 
running biome.
