### ISSUE TITLE
🐛 Biome CLI & VS Code Format on Save behavior is different / inconsistent

### ISSUE THREAD

**Issue by cliffordfajardo** [biomejs/biome-vscode#451]
### Description
I setup biome in my typescript project & the `format` behavior is inconsistent between the biome CLI and VSCode extension.

**Why is this an issue?**
  - First-time users of Biome may find it confusing and frustrating when the `format` behavior is inconsistent between the CLI  and the VSCode extension.
  - I spent 1 hour fiddling with things until I stumbled upon a thread suggesting to [override the language settings individually](https://github.com/biomejs/biome-vscode/discussions/230)

I'm a fan of biome; I think there are still opportunities to reduce friction with getting started with good defaults.

https://github.com/user-attachments/assets/94a14ce2-3909-4169-9af8-d323cc814019

## Steps to reproduce
<details>

Ensure you have the [biome extension](https://marketplace.visualstudio.com/items?itemName=biomejs.biome) installed in your vscode.

**Download small example code i created:**

```sh
git clone https://github.com/cliffordfajardo/biome-vscode-cli-inconsistency-bug1.git
cd biome-vscode-cli-inconsistency-bug1
```

**Reproduce inconsistency between CLI and VSCode**
```sh
# 1. run the lint command defined in our package.json's scripts section; 
#    you should see no changes being reported
# ----------------------------------------------------
npm run lint

# 2. Open scripts/file1.ts in your editor & save the file &  you should see the file change. I suspect the format on save is no longer using biome & instead using the default vscode formatter settings for javascript/typescript/typescriptreact etc
# ----------------------------------------------------


# 4.  Run `npm run lint` to see biome undo the format on save behavior.
npm run lint


# 5. Uncomment the lines in .vscode/settings.json below the NOTE section
#    Then open scripts/file1.ts in your editor & save the file & you should not see any changes. With the new settings, biome is now using the default vscode formatter.


# 6.  Run `npm run lint` to see biome run lint on the file & you should see no changes.
```

</details>

## Observations
Having a `.vscode/settings.json` file in your project with  `"editor.defaultFormatter" : "biomejs.biome`  is not enough to enforce VS Code to follow the same rules that the CLI (or more specifically biome.json) has defined, we need to be more explicit?

<details>

❌ Not enough:
```
{
	"editor.formatOnSave": true,
	"editor.defaultFormatter": "biomejs.biome"
}
```

✅ Aligns with CLI and ovveride vscode settings correctly (at least for typescript/js/react project):
```
{

	"editor.formatOnSave": true,
	"editor.defaultFormatter": "biomejs.biome",
	"[javascript]": {
		"editor.defaultFormatter": "biomejs.biome"
	},
	"[typescript]": {
		"editor.defaultFormatter": "biomejs.biome"
	},
	"[typescriptreact]": {
		"editor.defaultFormatter": "biomejs.biome"
	},
	"[json]": {
		"editor.defaultFormatter": "biomejs.biome"
	}
}
```

</details>

### Expected behavior
Format on save and biome CLI should behave the same.

## Opportunities
Have biome init command detect if there is a .vscode/settings.json file, if not, create one.
I think its safer to have this than to not have it for users using vscode. Explicit > implicit

### System Details
macOS -- i dont think OS is an issue
Biome v 1.9.4 (latest) -- i dont think the version is the issue
Vscode version 2.3.0 -- i dont think vscode version is issue

## References
- https://github.com/biomejs/biome-vscode/discussions/230
- Link to a minimal reproduction: https://github.com/cliffordfajardo/biome-vscode-cli-inconsistency-bug1

**Comment by ematipico** [comment]
This is a complexity added by VSCode, and we can't do much about it. 

See https://github.com/biomejs/biome-vscode/discussions/230 and https://x.com/colinhacks/status/1841219884287737886
