### ISSUE TITLE
File size limit popup opens multiple times when moving through a big file.

### ISSUE THREAD

**Issue by espenja** [biomejs/biome-vscode#48]
When looking at large files, this error message will pop up in the Biome output window every time you move through the file by arrows, mouse or any other action:

```
[Error - 12:54:55 AM] Request textDocument/codeAction failed.
  Message: Size of packages\apps\api\public\swagger\swagger-ui-bundle.js is 1.3 MiB which exceeds configured maximum of 1.0 MiB for this project. The file size limit exists to prevent us inadvertently slowing down and loading large files that we shouldn't.
  Code: -32603 
```

Similarly, a popup will appear for every move or action taken in the file:  

![image](https://github.com/biomejs/biome-vscode/assets/1131968/6a220861-37ce-40c2-8400-f403ed719af7)

Is it possible to make this popup only appear once, or once per unique file?
The popup does not close unless manually closed, it takes away focus and is generally annoying.
Sometimes you need to poke around in your build files or other packages, and this quickly gets tiresome.

I think the size limit is there for a reason, and that's a good thing. Instead of going around this to "fix" my problem, I would like to be annoyed only once by this popup.

**Comment by ematipico** [comment]
Hey @espenja , thank you for your feedback.

We changed the behaviour, and the LSP won't show any toasts/pop-ups anymore, instead, it will log those messages.

FYI this isn't a VSCode things, but something implemented in the LSP code :)
