### ISSUE TITLE
🐛 Cannot format TypeScript in VS Code

### ISSUE THREAD

**Issue by victorz** [biomejs/biome-vscode#5]
### Environment information

```block
I don't have a "biome" binary installed. I just installed the VS Code extension.
```

### What happened?

I installed the VS Code extension and followed the instructions in its README to configure the default formatter for TypeScript files. I'm used to this procedure so I know how to do so.

Also tried running the command "Format Document" with Biome as the default formatter for TypeScript, and I'm met with this dialog:

![image](https://github.com/biomejs/biome/assets/7494/193587e4-fc99-4600-9811-52fc2a6db99b)

Same with JavaScript files:

![image](https://github.com/biomejs/biome/assets/7494/76432ce3-e5f2-494b-922a-2fb624514adc)

Prettier works fine... 🤷

### Expected result

I expect it to be able to format TypeScript, since that's what it says in the README.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
The README has been updated to state better that a `biome.json` file is required for the extension to start.

I'll close this issue for now, but feel free to open another issue or PR if you think something is still unclear.
