### ISSUE TITLE
The VSCode extension fails to work when the Github API rate limit is reached.

### ISSUE THREAD

**Issue by zoolsher** [biomejs/biome-vscode#56]
I encountered the API rate limit, resulting in the malfunctioning of the VSCode extension. I found this error:

```txt
`releases.filter` is not a function
```

I examined the log and discovered that the return from the `getVersions` function is not an array when retrieving from `https://api.github.com/repos/biomejs/biome/releases?per_page=100`.

```json
{
  "message": "API rate limit exceeded for[IP.IP.IP.IP]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

> BTW. Thanks for creating biome. It helps me a lot!

**Comment by nhedger** [comment]
Hey @zoolsher,

Thanks for opening this issue.

I'm curious as to how you encountered this rate limit because I've encountered it, too, and then decided to implement a mechanism for caching the versions to prevent this from happening.

Did you do anything out of the ordinary? I'd love to investigate the issue.

Thanks

**Comment by zoolsher** [comment]
Hi @nhedger ,

I'm not certain, but it seems that everything works smoothly once I connect to a global VPN. During my daily development, I often encounter API limits in GitHub-related apps such as star-history.

Thanks!

**Comment by nhedger** [comment]
Ah interesting. Any chance you share an IP with other users? I remember experiencing something similar when I worked in a large office where our external was the same for everyone.

This could potentially explain why you hit the rate limit this fast.

**Comment by zoolsher** [comment]
Yes! I am currently working in a large office and I believe we are sharing the same IP address.
