### ISSUE TITLE
Unverified Domain

### ISSUE THREAD

**Issue by Barzi-Ahmed** [biomejs/biome-vscode#62]
Hello,

Please verify your domain for your extension, in order to get the verification badge to boost integrity.

See, ESLint has it, but Biome doesn't. 

![Capture](https://github.com/biomejs/biome-vscode/assets/135956133/b6998ad9-9b08-4168-a55d-422b020bf652)
![Capture2](https://github.com/biomejs/biome-vscode/assets/135956133/af70c2d3-93f4-49b9-9d14-e7fbd7277c04)

[**It should be easy to implement.**](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher)

**Comment by nhedger** [comment]
Good idea @Barzi-Ahmed, thanks for suggesting.

@ematipico This requires access to the DNS zone of `biomejs.dev`, so I'm guessing you're the one that would have to do the procedure.

**Comment by ematipico** [comment]
Oh right, we moved under Netlify so we lost that identification. I'll take care of it

**Comment by ematipico** [comment]
That's done. The docs say that this will be take up to 5 business day.
