### ISSUE TITLE
Biome is not fully allowing typescript as a format on install.

### ISSUE THREAD

**Issue by Eveeifyeve** [biomejs/biome-vscode#67]
I've noticed in your biome vscode extension it didn't support typescript.

I reloaded an it was there. maybe there's some weird bug going on when you install it? 

### Solutions I have found.
Force a reload on first install using preinstall and "preInstallMessage" in package.json

### Help?
**But I am to help out on this issue of concern if needed I know typescript, javascript and rust, So I can help you if needed.**

**Comment by Eveeifyeve** [comment]
![proof](https://cdn.discordapp.com/attachments/1185112568717639740/1192389020546768896/IMG_0114.jpg?ex=65a8e5d0&is=659670d0&hm=eaafad18d9265d9c69cd6f81a105019208f60a464a21318afe66e5618a4dec57&)

**Comment by nhedger** [comment]
I can't seem to reproduce this issue.

https://github.com/biomejs/biome-vscode/assets/649677/8a8a80ef-9050-4e45-824f-d26ff74e79e5

Would you mind providing detailed steps as well as:

- version of Biome
- version of the extension
- version of VS Code
- Operating system

**Comment by Eveeifyeve** [comment]
### Steps to reproduce
1. Open VsCode
2. Install the extension 
3. Press CMD + SHIFT + P 
4. Type Settings Json and select user settings.
5. Set BiomeJs/biome as default and javascript.
6. Save the json file.
7. Try to format.

### Details 
- Biome Extension v2.0.0
- @Biomejs/Biome 1.4.1
- VsCode 1.85.1
- MacOS Sonoma 14.2

**Comment by nhedger** [comment]
Just to be clear, when you say "try to reformat", do you mean the settings file ?

Also, do you use a shortcut that uses the default formatted or do you explicitly choose a formatted using the command palette?

**Comment by ematipico** [comment]
I see the issue I think.

`settings.json` is identified as a file "JSON with comments", which is a JSONC file. This is a VSCode thing. 
Biome can only handle `.json` files with comments if you opt-in: https://biomejs.dev/reference/configuration/#jsonparserallowcomments

**Comment by Eveeifyeve** [comment]
Yeah that is just an example I used but the same thing can be applyed to a ts file.


> I see the issue I think.
> 
> `settings.json` is identified as a file "JSON with comments", which means that it allows comments in a JSON file (usually not valid). This is a VSCode thing. Biome can only handle `.json` files with comments if you opt-in: https://biomejs.dev/reference/configuration/#jsonparserallowcomments

**Comment by yLuuuucas** [comment]
Hi, I have the same problem after updating vscode to 1.85.1

- VsCode 1.85.1
- @biomejs/biome 1.5.0
- Biome Extension v2.1.1

**Comment by Eveeifyeve** [comment]
Extension 'Biome' is configured as formatter but it cannot format 'TypeScript'-files

**Comment by thelinuxlich** [comment]
Same issue here with latest VSCode, Biome extension and biome package on the project.

**Comment by ematipico** [comment]
> Same issue here with latest VSCode, Biome extension and biome package on the project.

Have you tried to reload the LSP server? There's a command for that

**Comment by nhedger** [comment]
Hey,

This issue hasn't seen any activity for some time so I'll close it for now, and we haven't been able to reproduce it, so I'll close it for now. Feel free to open a new issue with detailed instructions on how to reproduce.

**Comment by david-04** [comment]
Hey Nicolas. The problem occurs when the environment variable `BIOME_CONFIG_PATH` is set. This was a well-working approach to have custom global settings that could be overridden by a project-specific `biome.json`.

This functionality broke in two stages. First, it stopped using the custom configuration at all. When `BIOME_CONFIG_PATH` was set, it would always use Biome's standard settings. It not only ignored the configured path but also any local `biome.json` within the project.

A few weeks later, it stopped formatting altogether and now only shows the error `Extension 'Biome' is configured as formatter but it cannot format 'TypeScript'-files` when  `BIOME_CONFIG_PATH` is set.

I don't know if it's down to the VSCode extension or Biome itself.

Are there any plans to add a config setting for a global custom config file? This would remove the need to set the environment variable.

**Comment by ematipico** [comment]
I believe `BIOME_CONFIG_PATH` never worked. We don't have such variable in our source code, and we don't document it

**Comment by david-04** [comment]
It's documented [here](https://biomejs.dev/reference/cli/#biome-lsp-proxy).

**Comment by ematipico** [comment]
I completely forgot to add it at the end of the page. Thank you
